#!/bin/sh
# ------------------------------------------------------------------------
# drv - GT.M and PROFILE/Anyware application driver script.
#
# Description: 
# This script will put the user at the PROFILE/Anyware login screen for
# the directory in which it resides.
#
# Input: None 
#
# Output: Places the user at the PROFILE/Anyware login screen.
#
# Usage: drv or /directory_path/drv
#	 $ /ibsprod/drv
#	 or
#	 $ cd /ibsprod
#        $ drv
# ------------------------------------------------------------------------
# Processing starts at main()
ARG0=$0
if [ ! -f ${ARG0} ] ; then
   echo "Usage: drv or /directory_path/drv"
   return 1
fi

. `dirname ${ARG0}`/gtmenv

main()
{
$gtm_dist/mumps -run SCADRV
}
main
