#!/bin/ksh
# ------------------------------------------------------------------------
# Description: 
# This script will define a GT.M and PROFILE/Anyware environment variables
# which are client and/or custom for the directory from which it is
# called.
#
# Input: None
#
# Output: Assigns GT.M and PROFILE/Anyware environment variables
#
# Usage: Is called from the script gtmenv (. /${DIR}/gtmenv1).
#
# Setup: Examples of variables defined in gtmenv1.
#   --- FMS Setup and FMS Autopost --- 
# 	FMS=/fmsprod
#	fmspost=AUTOPOST.sh
#	SCA_fmspost=AUTOPOST.sh
#	fmsnodir=production_node::${FMS}
#	SCAU_FMS_UBG=${FMS}/gbls/mumps.fms
# 	export FMS fmspost SCA_fmspost fmsnodir SCAU_FMS_UBG
#   --- Server Setup ---
#	SCA_CS_ST_SCA_IBS="MTM_IBSPROD"
#	export SCA_CS_ST_SCA_IBS
#   --- EFT Setup ---
#	SCAU_EFTSEND=${DIR}/spool
#	SCAU_EFTREC=${DIR}/spool
#	export SCAU_EFTSEND SCAU_EFTREC
# ------------------------------------------------------------------------

# The following is for support of multiple GT.M versions

gtm_log=/tmp
gtm_tmp=/tmp
export gtm_log gtm_tmp

# New external call for GT.M V5.2
#export GTMXC_extcall=${DIR}/extcall_V1.2/extcall.xc
export SCA_GTM=${DIR}
gtm_chset=M
export gtm_chset
export TERM=vt420

SCA_CS_ST_SCA_IBS="MTM_PIPV01"
export SCA_CS_ST_SCA_IBS

SCAU_DB=GTM
export SCAU_DB=GTM

GTMXC_alerts="/SCA/sca_gtm/alerts/alerts.xc"
#GTMXC_alerts="${SCA_GTM}/extcall_V1.2/alerts.xc"
#GTMXC_extcall="${SCA_GTM}/extcall_V1.2/extcall.xc"
GTMXC_extcall="/SCA/sca_gtm/extcall/extcall.xc"
GTMXC_mtm="${SCA_GTM}/mtm_V2.4.5/mtm.xc"
GTMXC_mq="${SCA_GTM}/mq_V1.0.1/mq.xc"
export GTMXC_alerts GTMXC_extcall GTMXC_mtm GTMXC_mq
