#!/bin/bash
# ------------------------------------------------------------------------
# Description: 
# This script will define a GT.M and PROFILE/Anyware environment variables
# which are client and/or custom for the directory from which it is
# called.
#
# Input: None
#
# Output: Assigns GT.M and PROFILE/Anyware environment variables
#
# Usage: Is called from the script gtmenv (. /${DIR}/gtmenv1).
#
# Setup: Examples of variables defined in gtmenv1.
#   --- FMS Setup and FMS Autopost --- 
# 	FMS=/fmsprod
#	fmspost=AUTOPOST.sh
#	SCA_fmspost=AUTOPOST.sh
#	fmsnodir=production_node::${FMS}
#	SCAU_FMS_UBG=${FMS}/gbls/mumps.fms
# 	export FMS fmspost SCA_fmspost fmsnodir SCAU_FMS_UBG
#   --- Server Setup ---
#	SCA_CS_ST_SCA_IBS="MTM_DEVM27"
#	export SCA_CS_ST_SCA_IBS
#   --- EFT Setup ---
#	SCAU_EFTSEND=${DIR}/spool
#	SCAU_EFTREC=${DIR}/spool
#	export SCAU_EFTSEND SCAU_EFTREC
# ------------------------------------------------------------------------

# The following is for support of multiple GT.M versions

gtm_log=/tmp
gtm_tmp=/tmp
export gtm_log gtm_tmp

# Added by Bhaskar for V5.4-000
gtm_noundef="YES" ; export gtm_noundef
gtm_icu_version=4.8 ; export gtm_icu_version

# New external call for GT.M V5.2
export GTMXC_extcall=$DIR/extcall_V1.2/extcall.xc
export SCA_GTM=$DIR

######### Set-up for $ZCHSET (uncomment one block below)
# For $ZCHSET="UTF-8"
#
export gtm_chset=UTF-8
#export gtm_chset=M
export LC_CTYPE=en_US.UTF-8
#export LD_LIBRARY_PATH=/usr/lib
# For $ZCHSET="M"
#
#export gtm_chset=M

#export TERM=vt420

SCA_CS_ST_SCA_IBS="MTM_PIPV02"
export SCA_CS_ST_SCA_IBS

SCAU_DB=GTM
export SCAU_DB=GTM

GTMXC_alerts="${SCA_GTM}/extcall_V1.2/alerts.xc"
GTMXC_extcall="${SCA_GTM}/extcall_V1.2/extcall.xc"
GTMXC_mtm="${SCA_GTM}/mtm_V2.4.5/mtm.xc"
GTMXC_mq="${SCA_GTM}/mq_V1.0.1/mq.xc"
export GTMXC_alerts GTMXC_extcall GTMXC_mtm GTMXC_mq

# ================ ================ ================ ================
# FSCW 2007-07-03
#
# Set up the PSL package search list SCAU_PACKAGES.
# A Standard Profile environment will distinguish the following
# packages:
# * #PACKAGE framework    // for the Profile Framework modules
# * #PACKAGE profile      // for the standard Profile Application modules
# * #PACKAGE custom       // for custom extensions to Profile
#
# Modules that do not specify a PACKAGE will end up in SCAU_CRTNS.
# PSL modules will be located by searching the directories in
# SCAU_PACKAGES from left to right.
# Because the PSL code generator will put the .m file in the directory
# where it found the .psl file, all subdirectories that are listed in
# SCAU_PACKAGES shall also be included as directories in the GT.M routine
# search list, and they shall occur in the same order.
# Note that this puts SCAU_CRTNS itself after its subdirectories.
#
SCAU_PACKAGES="custom:profile:framework"
export SCAU_PACKAGES

# FSCW, 2009-02-08
#   set GT.M editor to pico
#export EDITOR="/usr/bin/pico"
