#!/bin/ksh
tmp=`dirname $0` ; cd $tmp
. ./gtmenv
$gtm_dist/mupip journal -recover -backward gbls/mumps.mjl \
 && $gtm_dist/mupip set -journal="enable,on,before" -noprev -file gbls/mumps.dat \
 && rm -f gbls/mumps.mjl_*
rm -f *.mj[oe]

