#!/bin/ksh
cd `dirname $0`
rm -f *.mj[oe]
SCA_ERROR_DIR=$PWD/extcall_V1.2/alerts ; export SCA_ERROR_DIR
ALERT_SCRIPT=$PWD/extcall_V1.2/alerts/sca_alert.sh ; export ALERT_SCRIPT
. ./gtmenv
./mtm/PIPV01
sleep 5
$gtm_dist/mupip journal -recover -backward gbls/mumps.mjl \
 && $gtm_dist/mupip set -journal="enable,on,before" -file gbls/mumps.dat \
 && ./dm <<EOF
do JOB^PBSUTL("SCA\$IBS",2)
halt
EOF
find gbls -iname mumps.mjl_* -mtime +3 -exec rm -v {} \;
