#!/bin/sh
cd `dirname $0`
ps -ef | grep mtm | grep -v grep | awk '{print $2}' | xargs kill 2>/dev/null
ps -ef | grep mumps | grep -v grep | awk '{print $2}' | xargs kill 2>/dev/null
. ./gtmenv
sleep 5
$gtm_dist/mupip rundown -file gbls/mumps.dat
