 ; 
 ; **** Routine compiled from DATA-QWIK Filer RecordDBTBL9 ****
 ; 
 ; 02/24/2010 18:40 - pip
 ; 
 ;
 ; Record Class code for table DBTBL9
 ;
 ; Generated by PSLRecordBuilder on 02/24/2010 at 18:40 by
 ;
vcdmNew() ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordDBTBL9",vobj(vOid,-2)=0,vobj(vOid)=""
 S vobj(vOid,-3)=""
 S vobj(vOid,-4)=""
 S vobj(vOid,-5)=""
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord0(v1,v2,v3,vfromDbSet) ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordDBTBL9"
 S vobj(vOid)=$G(^DBTBL(v1,9,v2,v3))
 I vobj(vOid)="",'($D(^DBTBL(v1,9,v2,v3))#2)
 S vobj(vOid,-2)=1
 I $T K vobj(vOid) S $ZE="0,"_$ZPOS_",%PSL-E-RECNOFL,,DBTBL9",$EC=",U1001,"
 S vobj(vOid,-3)=v1
 S vobj(vOid,-4)=v2
 S vobj(vOid,-5)=v3
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord1(v1,v2,v3,vfromDbSet) ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordDBTBL9"
 S vobj(vOid)=$G(^DBTBL(v1,9,v2,v3))
 I vobj(vOid)="",'($D(^DBTBL(v1,9,v2,v3))#2)
 S vobj(vOid,-2)='$T
 S vobj(vOid,-3)=v1
 S vobj(vOid,-4)=v2
 S vobj(vOid,-5)=v3
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord0Opt(v1,v2,v3,vfromDbSet,v2out) ; 
 N dbtbl9
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S dbtbl9=$G(^DBTBL(v1,9,v2,v3))
 I dbtbl9="",'($D(^DBTBL(v1,9,v2,v3))#2)
 S v2out=1
 I $T S $ZE="0,"_$ZPOS_",%PSL-E-RECNOFL,,DBTBL9",$EC=",U1001,"
 ;*** End of code by-passed by compiler ***
 Q dbtbl9
 ;
vRCgetRecord1Opt(v1,v2,v3,vfromDbSet,v2out) ; 
 N dbtbl9
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S dbtbl9=$G(^DBTBL(v1,9,v2,v3))
 I dbtbl9="",'($D(^DBTBL(v1,9,v2,v3))#2)
 S v2out='$T
 ;*** End of code by-passed by compiler ***
 Q dbtbl9
 ;
vBypassSave(this) ; 
 D vSave(this,"/NOJOURNAL/NOTRIGAFT/NOTRIGBEF/NOVALDD/NOVALREQ/NOVALRI/NOVALST",0)
 Q 
 ;
vSave(this,vRCparams,vauditLogSeq) ; 
 N vRCaudit N vRCauditIns
 N %O S %O=$G(vobj(this,-2))
 I ($get(vRCparams)="") S vRCparams="/CASDEL/INDEX/JOURNAL/LOG/TRIGAFT/TRIGBEF/UPDATE/VALDD/VALFK/VALREQ/VALRI/VALST/"
 I (%O=0) D
 .	D AUDIT^UCUTILN(this,.vRCauditIns,1,"|")
 .	D vRCsetDefaults(this)
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,%O)
 .	D vRCmiscValidations(this,vRCparams,%O)
 .	D vRCupdateDB(this,%O,vRCparams,.vRCaudit,.vRCauditIns)
 .	Q 
 E  I (%O=1) D
 .	D AUDIT^UCUTILN(this,.vRCaudit,1,"|")
 .	I ($D(vobj(this,-100,"1*","%LIBS"))&($P($E($G(vobj(this,-100,"1*","%LIBS")),5,9999),$C(124))'=vobj(this,-3)))!($D(vobj(this,-100,"2*","PRITABLE"))&($P($E($G(vobj(this,-100,"2*","PRITABLE")),5,9999),$C(124))'=vobj(this,-4)))!($D(vobj(this,-100,"3*","JRNID"))&($P($E($G(vobj(this,-100,"3*","JRNID")),5,9999),$C(124))'=vobj(this,-5))) D vRCkeyChanged(this,vRCparams,.vRCaudit) Q 
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForUpdate(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD1(this)
 .	D vRCmiscValidations(this,vRCparams,%O)
 .	D vRCupdateDB(this,%O,vRCparams,.vRCaudit,.vRCauditIns)
 .	Q 
 E  I (%O=2) D
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,%O)
 .	D vRCmiscValidations(this,vRCparams,2)
 .	Q 
 E  I (%O=3) D
 .	  N V1,V2,V3 S V1=vobj(this,-3),V2=vobj(this,-4),V3=vobj(this,-5) Q:'($D(^DBTBL(V1,9,V2,V3))#2) 
 .	D vRCdelete(this,vRCparams,.vRCaudit,0)
 .	Q 
 Q 
 ;
vcheckAccessRights() ; 
 Q ""
 ;
vinsertAccess(userclass) ; 
 Q 1
 ;
vinsertOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vupdateAccess(userclass) ; 
 Q 1
 ;
vupdateOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vdeleteAccess(userclass) ; 
 Q 1
 ;
vdeleteOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vselectAccess(userclass,restrict,from) ; 
 S (restrict,from)=""
 Q 1
 ;
vselectOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vselectOptmOK(userclass,dbtbl9,vkey1,vkey2,vkey3) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vgetLogging() ; 
 Q "0"
 ;
logUserclass(operation) ; 
 I (operation="INSERT") Q 0
 E  I (operation="UPDATE") Q 0
 E  I (operation="DELETE") Q 0
 E  I (operation="SELECT") Q 0
 Q 0
 ;
vlogSelect(statement,using) ; 
 Q 0
 ;
columnList() ; 
 Q $$vStrRep("%LIBS,DES,EFD,EXCOLUMN,IFCOND,INCOLUMN,JRNID,MODE,PARFID,PRITABLE,QUERY1,QUERY2,SEQ,SUBTABLE,TIME,TLD,TRANTYPE,USER",",",$char(9),0,0,"")
 ;
columnListBM() ; 
 Q ""
 ;
columnListCMP() ; 
 Q $$vStrRep("PTBLDES,SUBTBLDE",",",$char(9),0,0,"")
 ;
getColumnMap(map) ; 
 ;
 S map(-5)="JRNID:T:"
 S map(-4)="PRITABLE:U:"
 S map(-3)="%LIBS:T:"
 S map(-1)="DES:T:1;EFD:T:3;EXCOLUMN:U:6;IFCOND:T:15;INCOLUMN:U:7;MODE:T:5;PARFID:T:13;QUERY1:T:11;QUERY2:T:12;SEQ:N:8;SUBTABLE:U:2;TIME:C:14;TLD:D:9;TRANTYPE:T:4;USER:T:10"
 Q 
 ;
vlegacy(processMode,params) ; 
 N vTp
 I (processMode=2) D
 .	N dbtbl9 S dbtbl9=$$vRCgetRecord0^RecordDBTBL9(%LIBS,PRITABLE,JRNID,0)
 .	S vobj(dbtbl9,-2)=2
 . S vTp=($TL=0) TS:vTp (vobj):transactionid="CS" D vSave^RecordDBTBL9(dbtbl9,$$initPar^UCUTILN(params)) K vobj(dbtbl9,-100) S vobj(dbtbl9,-2)=1 TC:vTp  
 .	K vobj(+$G(dbtbl9)) Q 
 Q 
 ;
vhasLiterals() ; 
 Q 0
 ;
vRCmiscValidations(this,vRCparams,processMode) ; 
 I (("/"_vRCparams_"/")["/VALST/")  N V1,V2,V3 S V1=vobj(this,-3),V2=vobj(this,-4),V3=vobj(this,-5) I '(''($D(^DBTBL(V1,9,V2,V3))#2)=''processMode) D
 .	N errmsg
 .	I (+processMode'=+0) S errmsg=$$^MSG(7932)
 .	E  S errmsg=$$^MSG(2327)
 .	D throwError(errmsg)
 .	Q 
 I (("/"_vRCparams_"/")["/VALFK/") D vRCcheckForeignKeys(this)
 I (("/"_vRCparams_"/")["/VALRI/") D vRCsetForeignKeys(this)
 Q 
 ;
vRCupdateDB(this,processMode,vRCparams,vRCaudit,vRCauditIns) ; 
 I '(("/"_vRCparams_"/")["/NOUPDATE/") D
 .  S $P(vobj(this),$C(124),9)=$P($H,",",1)
 .  S $P(vobj(this),$C(124),14)=$P($H,",",2)
 .	I '(+$P($G(vobj(this,-100,"0*","USER")),$C(124),2)&($P($E($G(vobj(this,-100,"0*","USER")),5,9999),$C(124))'=$P(vobj(this),$C(124),10)))  S $P(vobj(this),$C(124),10)=$E($$USERNAM^%ZFUNC,1,20)
 .	;   #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; GROUP=BYPASS
 .	;*** Start of code by-passed by compiler
 .	if $D(vobj(this)) S ^DBTBL(vobj(this,-3),9,vobj(this,-4),vobj(this,-5))=vobj(this)
 .	;*** End of code by-passed by compiler ***
 .	Q 
 Q 
 ;
vRCdelete(this,vRCparams,vRCaudit,isKeyChange) ; 
 ;  #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; Group=BYPASS
 ;*** Start of code by-passed by compiler
 ZWI ^DBTBL(vobj(this,-3),9,vobj(this,-4),vobj(this,-5))
 ;*** End of code by-passed by compiler ***
 Q 
 ;
vRCsetDefaults(this) ; 
 I ($P(vobj(this),$C(124),8)="")  S $P(vobj(this),$C(124),8)=1
 Q 
 ;
vRCchkReqForInsert(this) ; 
 I (vobj(this,-3)="") D vRCrequiredErr("%LIBS")
 I ($P(vobj(this),$C(124),1)="") D vRCrequiredErr("DES")
 I (vobj(this,-5)="") D vRCrequiredErr("JRNID")
 I (vobj(this,-4)="") D vRCrequiredErr("PRITABLE")
 I ($P(vobj(this),$C(124),2)="") D vRCrequiredErr("SUBTABLE")
 Q 
 ;
vRCchkReqForUpdate(this) ; 
 I (vobj(this,-3)="") D vRCrequiredErr("%LIBS")
 I (vobj(this,-4)="") D vRCrequiredErr("PRITABLE")
 I (vobj(this,-5)="") D vRCrequiredErr("JRNID")
 I ($D(vobj(this,-100,"0*","DES"))&($P($E($G(vobj(this,-100,"0*","DES")),5,9999),$C(124))'=$P(vobj(this),$C(124),1))),($P(vobj(this),$C(124),1)="") D vRCrequiredErr("DES")
 I ($D(vobj(this,-100,"0*","SUBTABLE"))&($P($E($G(vobj(this,-100,"0*","SUBTABLE")),5,9999),$C(124))'=$P(vobj(this),$C(124),2))),($P(vobj(this),$C(124),2)="") D vRCrequiredErr("SUBTABLE")
 Q 
 ;
vRCrequiredErr(column) ; 
 N ER S ER=0
 N RM S RM=""
 D SETERR^DBSEXECU("DBTBL9","MSG",1767,"DBTBL9."_column)
 I ER D throwError($get(RM))
 Q 
 ;
vRCsetForeignKeys(this) ; 
 I '(vobj(this,-4)="") S vfkey("^DBTBL("_""""_vobj(this,-3)_""""_","_1_","_""""_vobj(this,-4)_""""_")")="DBTBL9(%LIBS,PRITABLE) -> DBTBL1"
 Q 
 ;
vRCcheckForeignKeys(this) ; 
  N V1,V2 S V1=vobj(this,-3),V2=vobj(this,-4) I '($D(^DBTBL(V1,1,V2))) D throwError($$^MSG(8563,"DBTBL9(%LIBS,PRITABLE) -> DBTBL1"))
 Q 
 ;
vRCvalidateDD(this,processMode) ; 
 N ER S ER=0
 N RM S RM=""
 N errmsg N X
 I ($L(vobj(this,-3))>12) D vRCvalidateDDerr("%LIBS",$$^MSG(1076,12))
 I (vobj(this,-4)'=$ZCONVERT(vobj(this,-4),"U")) D vRCvalidateDDerr("PRITABLE",$$^MSG(1476))
 I ($L(vobj(this,-4))>25) D vRCvalidateDDerr("PRITABLE",$$^MSG(1076,25))
 I ($L(vobj(this,-5))>14) D vRCvalidateDDerr("JRNID",$$^MSG(1076,14))
 I ($L($P(vobj(this),$C(124),1))>40) D vRCvalidateDDerr("DES",$$^MSG(1076,40))
 I ($L($P(vobj(this),$C(124),3))>5) D vRCvalidateDDerr("EFD",$$^MSG(1076,5))
 I ($P(vobj(this),$C(124),6)'=$ZCONVERT($P(vobj(this),$C(124),6),"U")) D vRCvalidateDDerr("EXCOLUMN",$$^MSG(1476))
 I ($L($P(vobj(this),$C(124),6))>250) D vRCvalidateDDerr("EXCOLUMN",$$^MSG(1076,250))
 I ($L($P(vobj(this),$C(124),15))>255) D vRCvalidateDDerr("IFCOND",$$^MSG(1076,255))
 I ($P(vobj(this),$C(124),7)'=$ZCONVERT($P(vobj(this),$C(124),7),"U")) D vRCvalidateDDerr("INCOLUMN",$$^MSG(1476))
 I ($L($P(vobj(this),$C(124),7))>250) D vRCvalidateDDerr("INCOLUMN",$$^MSG(1076,250))
 I ($L($P(vobj(this),$C(124),5))>10) D vRCvalidateDDerr("MODE",$$^MSG(1076,10))
 I ($L($P(vobj(this),$C(124),13))>12) D vRCvalidateDDerr("PARFID",$$^MSG(1076,12))
 I ($L($P(vobj(this),$C(124),11))>100) D vRCvalidateDDerr("QUERY1",$$^MSG(1076,100))
 I ($L($P(vobj(this),$C(124),12))>100) D vRCvalidateDDerr("QUERY2",$$^MSG(1076,100))
 I '($P(vobj(this),$C(124),8)=""),'(+$P(vobj(this),$C(124),8)=$P(vobj(this),$C(124),8))  S $P(vobj(this),$C(124),8)=$$vRCtrimNumber($P(vobj(this),$C(124),8))
 S X=$P(vobj(this),$C(124),8) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("SEQ",$$^MSG(742,"N"))
 I ($P(vobj(this),$C(124),2)'=$ZCONVERT($P(vobj(this),$C(124),2),"U")) D vRCvalidateDDerr("SUBTABLE",$$^MSG(1476))
 I ($L($P(vobj(this),$C(124),2))>12) D vRCvalidateDDerr("SUBTABLE",$$^MSG(1076,12))
 S X=$P(vobj(this),$C(124),14) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("TIME",$$^MSG(742,"C"))
 S X=$P(vobj(this),$C(124),9) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("TLD",$$^MSG(742,"D"))
 I ($L($P(vobj(this),$C(124),4))>10) D vRCvalidateDDerr("TRANTYPE",$$^MSG(1076,10))
 I ($L($P(vobj(this),$C(124),10))>20) D vRCvalidateDDerr("USER",$$^MSG(1076,20))
 Q 
 ;
vRCvalidateDD1(this) ; 
 N ER S ER=0
 N RM S RM=""
 N errmsg N X
 I ($D(vobj(this,-100,"1*","%LIBS"))&($P($E($G(vobj(this,-100,"1*","%LIBS")),5,9999),$C(124))'=vobj(this,-3))) I ($L(vobj(this,-3))>12) D vRCvalidateDDerr("%LIBS",$$^MSG(1076,12))
 I (vobj(this,-4)'=$ZCONVERT(vobj(this,-4),"U")) D vRCvalidateDDerr("PRITABLE",$$^MSG(1476))
 I ($D(vobj(this,-100,"2*","PRITABLE"))&($P($E($G(vobj(this,-100,"2*","PRITABLE")),5,9999),$C(124))'=vobj(this,-4))) I ($L(vobj(this,-4))>25) D vRCvalidateDDerr("PRITABLE",$$^MSG(1076,25))
 I ($D(vobj(this,-100,"3*","JRNID"))&($P($E($G(vobj(this,-100,"3*","JRNID")),5,9999),$C(124))'=vobj(this,-5))) I ($L(vobj(this,-5))>14) D vRCvalidateDDerr("JRNID",$$^MSG(1076,14))
 I ($D(vobj(this,-100,"0*","DES"))&($P($E($G(vobj(this,-100,"0*","DES")),5,9999),$C(124))'=$P(vobj(this),$C(124),1))) I ($L($P(vobj(this),$C(124),1))>40) D vRCvalidateDDerr("DES",$$^MSG(1076,40))
 I ($D(vobj(this,-100,"0*","EFD"))&($P($E($G(vobj(this,-100,"0*","EFD")),5,9999),$C(124))'=$P(vobj(this),$C(124),3))) I ($L($P(vobj(this),$C(124),3))>5) D vRCvalidateDDerr("EFD",$$^MSG(1076,5))
 I ($P(vobj(this),$C(124),6)'=$ZCONVERT($P(vobj(this),$C(124),6),"U")) D vRCvalidateDDerr("EXCOLUMN",$$^MSG(1476))
 I ($D(vobj(this,-100,"0*","EXCOLUMN"))&($P($E($G(vobj(this,-100,"0*","EXCOLUMN")),5,9999),$C(124))'=$P(vobj(this),$C(124),6))) I ($L($P(vobj(this),$C(124),6))>250) D vRCvalidateDDerr("EXCOLUMN",$$^MSG(1076,250))
 I ($D(vobj(this,-100,"0*","IFCOND"))&($P($E($G(vobj(this,-100,"0*","IFCOND")),5,9999),$C(124))'=$P(vobj(this),$C(124),15))) I ($L($P(vobj(this),$C(124),15))>255) D vRCvalidateDDerr("IFCOND",$$^MSG(1076,255))
 I ($P(vobj(this),$C(124),7)'=$ZCONVERT($P(vobj(this),$C(124),7),"U")) D vRCvalidateDDerr("INCOLUMN",$$^MSG(1476))
 I ($D(vobj(this,-100,"0*","INCOLUMN"))&($P($E($G(vobj(this,-100,"0*","INCOLUMN")),5,9999),$C(124))'=$P(vobj(this),$C(124),7))) I ($L($P(vobj(this),$C(124),7))>250) D vRCvalidateDDerr("INCOLUMN",$$^MSG(1076,250))
 I ($D(vobj(this,-100,"0*","MODE"))&($P($E($G(vobj(this,-100,"0*","MODE")),5,9999),$C(124))'=$P(vobj(this),$C(124),5))) I ($L($P(vobj(this),$C(124),5))>10) D vRCvalidateDDerr("MODE",$$^MSG(1076,10))
 I ($D(vobj(this,-100,"0*","PARFID"))&($P($E($G(vobj(this,-100,"0*","PARFID")),5,9999),$C(124))'=$P(vobj(this),$C(124),13))) I ($L($P(vobj(this),$C(124),13))>12) D vRCvalidateDDerr("PARFID",$$^MSG(1076,12))
 I ($D(vobj(this,-100,"0*","QUERY1"))&($P($E($G(vobj(this,-100,"0*","QUERY1")),5,9999),$C(124))'=$P(vobj(this),$C(124),11))) I ($L($P(vobj(this),$C(124),11))>100) D vRCvalidateDDerr("QUERY1",$$^MSG(1076,100))
 I ($D(vobj(this,-100,"0*","QUERY2"))&($P($E($G(vobj(this,-100,"0*","QUERY2")),5,9999),$C(124))'=$P(vobj(this),$C(124),12))) I ($L($P(vobj(this),$C(124),12))>100) D vRCvalidateDDerr("QUERY2",$$^MSG(1076,100))
 I ($D(vobj(this,-100,"0*","SEQ"))&($P($E($G(vobj(this,-100,"0*","SEQ")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))),'($P(vobj(this),$C(124),8)=""),'(+$P(vobj(this),$C(124),8)=$P(vobj(this),$C(124),8))  S $P(vobj(this),$C(124),8)=$$vRCtrimNumber($P(vobj(this),$C(124),8))
 I ($D(vobj(this,-100,"0*","SEQ"))&($P($E($G(vobj(this,-100,"0*","SEQ")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))) S X=$P(vobj(this),$C(124),8) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("SEQ",$$^MSG(742,"N"))
 I ($P(vobj(this),$C(124),2)'=$ZCONVERT($P(vobj(this),$C(124),2),"U")) D vRCvalidateDDerr("SUBTABLE",$$^MSG(1476))
 I ($D(vobj(this,-100,"0*","SUBTABLE"))&($P($E($G(vobj(this,-100,"0*","SUBTABLE")),5,9999),$C(124))'=$P(vobj(this),$C(124),2))) I ($L($P(vobj(this),$C(124),2))>12) D vRCvalidateDDerr("SUBTABLE",$$^MSG(1076,12))
 I ($D(vobj(this,-100,"0*","TIME"))&($P($E($G(vobj(this,-100,"0*","TIME")),5,9999),$C(124))'=$P(vobj(this),$C(124),14))) S X=$P(vobj(this),$C(124),14) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("TIME",$$^MSG(742,"C"))
 I ($D(vobj(this,-100,"0*","TLD"))&($P($E($G(vobj(this,-100,"0*","TLD")),5,9999),$C(124))'=$P(vobj(this),$C(124),9))) S X=$P(vobj(this),$C(124),9) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("TLD",$$^MSG(742,"D"))
 I ($D(vobj(this,-100,"0*","TRANTYPE"))&($P($E($G(vobj(this,-100,"0*","TRANTYPE")),5,9999),$C(124))'=$P(vobj(this),$C(124),4))) I ($L($P(vobj(this),$C(124),4))>10) D vRCvalidateDDerr("TRANTYPE",$$^MSG(1076,10))
 I ($D(vobj(this,-100,"0*","USER"))&($P($E($G(vobj(this,-100,"0*","USER")),5,9999),$C(124))'=$P(vobj(this),$C(124),10))) I ($L($P(vobj(this),$C(124),10))>20) D vRCvalidateDDerr("USER",$$^MSG(1076,20))
 Q 
 ;
vRCvalidateDDerr(column,errmsg) ; 
 N ER S ER=0
 N RM S RM=""
 D SETERR^DBSEXECU("DBTBL9","MSG",979,"DBTBL9."_column_" "_errmsg)
 I ER D throwError($get(RM))
 Q 
 ;
vRCtrimNumber(str) ; 
 I ($E(str,1)="0") S str=$$vStrTrim(str,-1,"0") I (str="") S str="0"
 I (str["."),($E(str,$L(str))="0") S str=$$RTCHR^%ZFUNC(str,"0") I ($E(str,$L(str))=".") S str=$E(str,1,$L(str)-1) I (str="") S str="0"
 Q str
 ;
vRCkeyChanged(this,vRCparams,vRCaudit) ; 
 N vTp
 N newkeys N oldkeys N vRCauditIns
 N newKey1 S newKey1=vobj(this,-3)
 N oldKey1 S oldKey1=$S($D(vobj(this,-100,"1*","%LIBS")):$P($E(vobj(this,-100,"1*","%LIBS"),5,9999),$C(124)),1:vobj(this,-3))
 N newKey2 S newKey2=vobj(this,-4)
 N oldKey2 S oldKey2=$S($D(vobj(this,-100,"2*","PRITABLE")):$P($E(vobj(this,-100,"2*","PRITABLE"),5,9999),$C(124)),1:vobj(this,-4))
 N newKey3 S newKey3=vobj(this,-5)
 N oldKey3 S oldKey3=$S($D(vobj(this,-100,"3*","JRNID")):$P($E(vobj(this,-100,"3*","JRNID"),5,9999),$C(124)),1:vobj(this,-5))
  N V1,V2,V3 S V1=vobj(this,-3),V2=vobj(this,-4),V3=vobj(this,-5) I ($D(^DBTBL(V1,9,V2,V3))#2) D throwError($$^MSG(2327))
 S newkeys=newKey1_","_newKey2_","_newKey3
 S oldkeys=oldKey1_","_oldKey2_","_oldKey3
  S vobj(this,-3)=oldKey1
  S vobj(this,-4)=oldKey2
  S vobj(this,-5)=oldKey3
 S vRCparams=$$setPar^UCUTILN(vRCparams,"NOINDEX")
 I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,1)
 D vRCmiscValidations(this,vRCparams,1)
 D vRCupdateDB(this,1,vRCparams,.vRCaudit,.vRCauditIns)
  S vobj(this,-3)=newKey1
  S vobj(this,-4)=newKey2
  S vobj(this,-5)=newKey3
 N newrec S newrec=$$vReCp1(this)
 S vobj(newrec,-2)=0
 S vTp=($TL=0) TS:vTp (vobj):transactionid="CS" D vSave^RecordDBTBL9(newrec,$$initPar^UCUTILN($$initPar^UCUTILN("/NOVAL/NOCASDEL/NOJOURNAL/NOTRIGBEF/NOTRIGAFT/"))) K vobj(newrec,-100) S vobj(newrec,-2)=1 TC:vTp  
 D
 .	N %O S %O=1
 .	N ER S ER=0
 .	N RM S RM=""
 .	;   #ACCEPT Date=10/24/2008; Pgm=RussellDS; CR=30801; Group=ACCESS
 .	D CASUPD^DBSEXECU("DBTBL9",oldkeys,newkeys)
 .	I ER D throwError($get(RM))
 .	Q 
  S vobj(this,-3)=oldKey1
  S vobj(this,-4)=oldKey2
  S vobj(this,-5)=oldKey3
 S vRCparams=$$initPar^UCUTILN("/NOVAL/NOCASDEL/NOJOURNAL/NOTRIGBEF/NOTRIGAFT/")
 D vRCdelete(this,vRCparams,.vRCaudit,1)
  S vobj(this,-3)=newKey1
  S vobj(this,-4)=newKey2
  S vobj(this,-5)=newKey3
 K vobj(+$G(newrec)) Q 
 ;
throwError(MSG) ; 
 S $ZE="0,"_$ZPOS_","_"%PSL-E-DBFILER,"_$translate(MSG,",","~"),$EC=",U1001,"
 Q 
 ; ----------------
 ;  #OPTION ResultClass 1
vStrRep(object,p1,p2,p3,p4,qt) ; String.replace
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 ;
 I p3<0 Q object
 I $L(p1)=1,$L(p2)<2,'p3,'p4,(qt="") Q $translate(object,p1,p2)
 ;
 N y S y=0
 F  S y=$$vStrFnd(object,p1,y,p4,qt) Q:y=0  D
 .	S object=$E(object,1,y-$L(p1)-1)_p2_$E(object,y,1048575)
 .	S y=y+$L(p2)-$L(p1)
 .	I p3 S p3=p3-1 I p3=0 S y=$L(object)+1
 .	Q 
 Q object
 ; ----------------
 ;  #OPTION ResultClass 1
vStrTrim(object,p1,p2) ; String.trim
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 I p1'<0 S object=$$RTCHR^%ZFUNC(object,p2)
 I p1'>0 F  Q:$E(object,1)'=p2  S object=$E(object,2,1048575)
 Q object
 ; ----------------
 ;  #OPTION ResultClass 1
vStrFnd(object,p1,p2,p3,qt) ; String.find
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 ;
 I (p1="") Q $S(p2<1:1,1:+p2)
 I p3 S object=$ZCONVERT(object,"U") S p1=$ZCONVERT(p1,"U")
 S p2=$F(object,p1,p2)
 I '(qt=""),$L($E(object,1,p2-1),qt)#2=0 D
 .	F  S p2=$F(object,p1,p2) Q:p2=0!($L($E(object,1,p2-1),qt)#2) 
 .	Q 
 Q p2
 ;
vReCp1(v1) ; RecordDBTBL9.copy: DBTBL9
 ;
 Q $$copy^UCGMR(this)
