 ; 
 ; **** Routine compiled from DATA-QWIK Procedure MRPC121 ****
 ; 
 ; 02/24/2010 18:22 - pip
 ; 
MRPC121(RETURN,VERSION,REQUEST,CODE,CMPTOK,LOCFILE,OBJTYPE,OBJID,TOKEN,USER) ; 
 ;
 S ER=0
 S RM=""
 ;
 ; Version number of client message is not compatible with server
 I $get(VERSION)'=1 Q $$ERRMSG^PBSUTL($$^MSG(2951))
 ;
 I REQUEST="INITOBJ" S RETURN=$$INITOBJ1^TBXDQSVR(OBJTYPE,OBJID)
 E  I REQUEST="RETOBJ" S RETURN=$$RETOBJ1^TBXDQSVR(TOKEN)
 E  I REQUEST="INITCODE" S RETURN=$$INITCOD1^TBXDQSVR(CODE,CMPTOK)
 E  I REQUEST="CHECKOBJ" S RETURN=$$CHECKOB1^TBXDQSVR(LOCFILE,TOKEN)
 E  I REQUEST="SAVEOBJ" S RETURN=$$SAVEOBJ1^TBXDQSVR(LOCFILE,TOKEN,USER)
 E  I REQUEST="EXECCOMP" S RETURN=$$EXECCOM1^TBXDQSVR(LOCFILE,CMPTOK)
 E  I REQUEST="EXECREV" S RETURN=$$EXECREV1^TBXDQSVR(LOCFILE,CMPTOK)
 E  S ER=1 S RM=$$^MSG(1417,REQUEST)
 ;
 ; If an error occurred, format error message
 I $get(ER) S RETURN=$$ERRMSG^PBSUTL($get(RM))
 ;
 ; Otherwise, format RETURN from TBXDQSVR
 E  S RETURN=$$V2LV^MSG(.RETURN)
 Q ""
 ;  #OPTION ResultClass ON
vSIG() ; 
 Q "61161^48458^Dan Russell^2846" ; Signature - LTD^TIME^USER^SIZE
