 ; 
 ; **** Routine compiled from DATA-QWIK Filer RecordSCAU0 ****
 ; 
 ; 02/24/2010 18:40 - pip
 ; 
 ;
 ; Record Class code for table SCAU0
 ;
 ; Generated by PSLRecordBuilder on 02/24/2010 at 18:40 by
 ;
vcdmNew() ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordSCAU0",vobj(vOid,-2)=0,vobj(vOid)=""
 S vobj(vOid,-3)=""
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord0(v1,vfromDbSet) ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordSCAU0"
 S vobj(vOid)=$G(^SCAU(0,v1))
 I vobj(vOid)="",'($D(^SCAU(0,v1))#2)
 S vobj(vOid,-2)=1
 I $T K vobj(vOid) S $ZE="0,"_$ZPOS_",%PSL-E-RECNOFL,,SCAU0",$EC=",U1001,"
 S vobj(vOid,-3)=v1
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord1(v1,vfromDbSet) ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordSCAU0"
 S vobj(vOid)=$G(^SCAU(0,v1))
 I vobj(vOid)="",'($D(^SCAU(0,v1))#2)
 S vobj(vOid,-2)='$T
 S vobj(vOid,-3)=v1
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord0Opt(v1,vfromDbSet,v2out) ; 
 N scau0
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S scau0=$G(^SCAU(0,v1))
 I scau0="",'($D(^SCAU(0,v1))#2)
 S v2out=1
 I $T S $ZE="0,"_$ZPOS_",%PSL-E-RECNOFL,,SCAU0",$EC=",U1001,"
 ;*** End of code by-passed by compiler ***
 Q scau0
 ;
vRCgetRecord1Opt(v1,vfromDbSet,v2out) ; 
 N scau0
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S scau0=$G(^SCAU(0,v1))
 I scau0="",'($D(^SCAU(0,v1))#2)
 S v2out='$T
 ;*** End of code by-passed by compiler ***
 Q scau0
 ;
vBypassSave(this) ; 
 D vSave(this,"/NOJOURNAL/NOTRIGAFT/NOTRIGBEF/NOVALDD/NOVALREQ/NOVALRI/NOVALST",0)
 Q 
 ;
vSave(this,vRCparams,vauditLogSeq) ; 
 N vRCaudit N vRCauditIns
 N %O S %O=$G(vobj(this,-2))
 I ($get(vRCparams)="") S vRCparams="/CASDEL/INDEX/JOURNAL/LOG/TRIGAFT/TRIGBEF/UPDATE/VALDD/VALFK/VALREQ/VALRI/VALST/"
 I (%O=0) D
 .	D AUDIT^UCUTILN(this,.vRCauditIns,1,"|")
 .	D vRCsetDefaults(this)
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,%O)
 .	D vRCmiscValidations(this,vRCparams,%O)
 .	D vRCupdateDB(this,%O,vRCparams,.vRCaudit,.vRCauditIns)
 .	Q 
 E  I (%O=1) D
 .	D AUDIT^UCUTILN(this,.vRCaudit,1,"|")
 .	I ($D(vobj(this,-100,"1*","UCLS"))&($P($E($G(vobj(this,-100,"1*","UCLS")),5,9999),$C(124))'=vobj(this,-3))) D vRCkeyChanged(this,vRCparams,.vRCaudit) Q 
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForUpdate(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD1(this)
 .	D vRCmiscValidations(this,vRCparams,%O)
 .	D vRCupdateDB(this,%O,vRCparams,.vRCaudit,.vRCauditIns)
 .	Q 
 E  I (%O=2) D
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,%O)
 .	D vRCmiscValidations(this,vRCparams,2)
 .	Q 
 E  I (%O=3) D
 .	  N V1 S V1=vobj(this,-3) Q:'($D(^SCAU(0,V1))#2) 
 .	D vRCdelete(this,vRCparams,.vRCaudit,0)
 .	Q 
 Q 
 ;
vcheckAccessRights() ; 
 Q ""
 ;
vinsertAccess(userclass) ; 
 Q 1
 ;
vinsertOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vupdateAccess(userclass) ; 
 Q 1
 ;
vupdateOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vdeleteAccess(userclass) ; 
 Q 1
 ;
vdeleteOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vselectAccess(userclass,restrict,from) ; 
 S (restrict,from)=""
 Q 1
 ;
vselectOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vselectOptmOK(userclass,scau0,vkey1) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vgetLogging() ; 
 Q "0"
 ;
logUserclass(operation) ; 
 I (operation="INSERT") Q 0
 E  I (operation="UPDATE") Q 0
 E  I (operation="DELETE") Q 0
 E  I (operation="SELECT") Q 0
 Q 0
 ;
vlogSelect(statement,using) ; 
 Q 0
 ;
columnList() ; 
 N columns S columns=""
 S columns=columns_"CCPOPT,DEALEFD,DESC,MAXEFD,MAXFT,MAXIN,MAXREV,MAXWO,MENU,MULPIN,OACMAX,OACMIN,OVR,OVRFT,PINTRCK,PLSAUPD,PWDCHG,PWDLEN,PWDTRY,RBRCC,"
 S columns=columns_"RETTIME,RSTRCT,SECUCLS,SESHIS,UCLS,"
 Q $$vStrRep("CCPOPT,DEALEFD,DESC,MAXEFD,MAXFT,MAXIN,MAXREV,MAXWO,MENU,MULPIN,OACMAX,OACMIN,OVR,OVRFT,PINTRCK,PLSAUPD,PWDCHG,PWDLEN,PWDTRY,RBRCC,RETTIME,RSTRCT,SECUCLS,SESHIS,UCLS",",",$char(9),0,0,"")
 ;
columnListBM() ; 
 Q ""
 ;
columnListCMP() ; 
 Q $$vStrRep("",",",$char(9),0,0,"")
 ;
getColumnMap(map) ; 
 ;
 S map(-3)="UCLS:T:"
 S map(-1)="CCPOPT:N:19;DEALEFD:L:16;DESC:T:1;MAXEFD:N:7;MAXFT:N:14;MAXIN:N:26;MAXREV:N:27;MAXWO:N:8;MENU:T:2;MULPIN:L:24;OACMAX:$:17;OACMIN:$:18;OVR:L:10;OVRFT:N:15;PINTRCK:L:23;PLSAUPD:L:28;PWDCHG:N:4;PWDLEN:N:"
 S map(-1)=map(-1)_"3;PWDTRY:N:5;RBRCC:L:13;RETTIME:C:25;RSTRCT:L:9;SECUCLS:L:6;SESHIS:L:22"
 Q 
 ;
vlegacy(processMode,params) ; 
 N vTp
 I (processMode=2) D
 .	N scau0 S scau0=$$vRCgetRecord0^RecordSCAU0(UCLS,0)
 .	S vobj(scau0,-2)=2
 . S vTp=($TL=0) TS:vTp (vobj):transactionid="CS" D vSave^RecordSCAU0(scau0,$$initPar^UCUTILN(params)) K vobj(scau0,-100) S vobj(scau0,-2)=1 TC:vTp  
 .	K vobj(+$G(scau0)) Q 
 Q 
 ;
vhasLiterals() ; 
 Q 0
 ;
vRCmiscValidations(this,vRCparams,processMode) ; 
 I (("/"_vRCparams_"/")["/VALST/")  N V1 S V1=vobj(this,-3) I '(''($D(^SCAU(0,V1))#2)=''processMode) D
 .	N errmsg
 .	I (+processMode'=+0) S errmsg=$$^MSG(7932)
 .	E  S errmsg=$$^MSG(2327)
 .	D throwError(errmsg)
 .	Q 
 Q 
 ;
vRCupdateDB(this,processMode,vRCparams,vRCaudit,vRCauditIns) ; 
 I '(("/"_vRCparams_"/")["/NOUPDATE/") D
 .	I '(("/"_vRCparams_"/")["/NOLOG/") D
 ..		I (processMode=1) D ^DBSLOGIT(this,1,.vRCaudit) Q 
 ..		D ^DBSLOGIT(this,0,.vRCauditIns)
 ..		Q 
 .	;   #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; GROUP=BYPASS
 .	;*** Start of code by-passed by compiler
 .	if $D(vobj(this)) S ^SCAU(0,vobj(this,-3))=vobj(this)
 .	;*** End of code by-passed by compiler ***
 .	Q 
 Q 
 ;
vRCdelete(this,vRCparams,vRCaudit,isKeyChange) ; 
 I '(("/"_vRCparams_"/")["/NOLOG/") D ^DBSLOGIT(this,3)
 ;  #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; Group=BYPASS
 ;*** Start of code by-passed by compiler
 ZWI ^SCAU(0,vobj(this,-3))
 ;*** End of code by-passed by compiler ***
 Q 
 ;
vRCsetDefaults(this) ; 
 I ($P(vobj(this),$C(124),16)="")  S $P(vobj(this),$C(124),16)=0
 I ($P(vobj(this),$C(124),24)="")  S $P(vobj(this),$C(124),24)=0
 I ($P(vobj(this),$C(124),10)="")  S $P(vobj(this),$C(124),10)=0
 I ($P(vobj(this),$C(124),23)="")  S $P(vobj(this),$C(124),23)=0
 I ($P(vobj(this),$C(124),28)="")  S $P(vobj(this),$C(124),28)=0
 I ($P(vobj(this),$C(124),4)="")  S $P(vobj(this),$C(124),4)=30
 I ($P(vobj(this),$C(124),3)="")  S $P(vobj(this),$C(124),3)=3
 I ($P(vobj(this),$C(124),5)="")  S $P(vobj(this),$C(124),5)=3
 I ($P(vobj(this),$C(124),13)="")  S $P(vobj(this),$C(124),13)=0
 I ($P(vobj(this),$C(124),9)="")  S $P(vobj(this),$C(124),9)=0
 I ($P(vobj(this),$C(124),6)="")  S $P(vobj(this),$C(124),6)=0
 I ($P(vobj(this),$C(124),22)="")  S $P(vobj(this),$C(124),22)=0
 Q 
 ;
vRCchkReqForInsert(this) ; 
 I ($P(vobj(this),$C(124),16)="") D vRCrequiredErr("DEALEFD")
 I ($P(vobj(this),$C(124),24)="") D vRCrequiredErr("MULPIN")
 I ($P(vobj(this),$C(124),10)="") D vRCrequiredErr("OVR")
 I ($P(vobj(this),$C(124),23)="") D vRCrequiredErr("PINTRCK")
 I ($P(vobj(this),$C(124),28)="") D vRCrequiredErr("PLSAUPD")
 I ($P(vobj(this),$C(124),13)="") D vRCrequiredErr("RBRCC")
 I ($P(vobj(this),$C(124),9)="") D vRCrequiredErr("RSTRCT")
 I ($P(vobj(this),$C(124),6)="") D vRCrequiredErr("SECUCLS")
 I ($P(vobj(this),$C(124),22)="") D vRCrequiredErr("SESHIS")
 I (vobj(this,-3)="") D vRCrequiredErr("UCLS")
 Q 
 ;
vRCchkReqForUpdate(this) ; 
 I (vobj(this,-3)="") D vRCrequiredErr("UCLS")
 I ($D(vobj(this,-100,"0*","DEALEFD"))&($P($E($G(vobj(this,-100,"0*","DEALEFD")),5,9999),$C(124))'=$P(vobj(this),$C(124),16))),($P(vobj(this),$C(124),16)="") D vRCrequiredErr("DEALEFD")
 I ($D(vobj(this,-100,"0*","MULPIN"))&($P($E($G(vobj(this,-100,"0*","MULPIN")),5,9999),$C(124))'=$P(vobj(this),$C(124),24))),($P(vobj(this),$C(124),24)="") D vRCrequiredErr("MULPIN")
 I ($D(vobj(this,-100,"0*","OVR"))&($P($E($G(vobj(this,-100,"0*","OVR")),5,9999),$C(124))'=$P(vobj(this),$C(124),10))),($P(vobj(this),$C(124),10)="") D vRCrequiredErr("OVR")
 I ($D(vobj(this,-100,"0*","PINTRCK"))&($P($E($G(vobj(this,-100,"0*","PINTRCK")),5,9999),$C(124))'=$P(vobj(this),$C(124),23))),($P(vobj(this),$C(124),23)="") D vRCrequiredErr("PINTRCK")
 I ($D(vobj(this,-100,"0*","PLSAUPD"))&($P($E($G(vobj(this,-100,"0*","PLSAUPD")),5,9999),$C(124))'=$P(vobj(this),$C(124),28))),($P(vobj(this),$C(124),28)="") D vRCrequiredErr("PLSAUPD")
 I ($D(vobj(this,-100,"0*","RBRCC"))&($P($E($G(vobj(this,-100,"0*","RBRCC")),5,9999),$C(124))'=$P(vobj(this),$C(124),13))),($P(vobj(this),$C(124),13)="") D vRCrequiredErr("RBRCC")
 I ($D(vobj(this,-100,"0*","RSTRCT"))&($P($E($G(vobj(this,-100,"0*","RSTRCT")),5,9999),$C(124))'=$P(vobj(this),$C(124),9))),($P(vobj(this),$C(124),9)="") D vRCrequiredErr("RSTRCT")
 I ($D(vobj(this,-100,"0*","SECUCLS"))&($P($E($G(vobj(this,-100,"0*","SECUCLS")),5,9999),$C(124))'=$P(vobj(this),$C(124),6))),($P(vobj(this),$C(124),6)="") D vRCrequiredErr("SECUCLS")
 I ($D(vobj(this,-100,"0*","SESHIS"))&($P($E($G(vobj(this,-100,"0*","SESHIS")),5,9999),$C(124))'=$P(vobj(this),$C(124),22))),($P(vobj(this),$C(124),22)="") D vRCrequiredErr("SESHIS")
 Q 
 ;
vRCrequiredErr(column) ; 
 N ER S ER=0
 N RM S RM=""
 D SETERR^DBSEXECU("SCAU0","MSG",1767,"SCAU0."_column)
 I ER D throwError($get(RM))
 Q 
 ;
vRCvalidateDD(this,processMode) ; 
 N ER S ER=0
 N RM S RM=""
 N errmsg N X
 I ($L(vobj(this,-3))>12) D vRCvalidateDDerr("UCLS",$$^MSG(1076,12))
 S X=$P(vobj(this),$C(124),19) I '(X=""),'$$vCaEx1() D vRCvalidateDDerr("CCPOPT",$$^MSG(1485,X))
 I '(($P(vobj(this),$C(124),16)=1)!($P(vobj(this),$C(124),16)=0)) D vRCvalidateDDerr("DEALEFD",$$^MSG(742,"L"))
 I ($L($P(vobj(this),$C(124),1))>40) D vRCvalidateDDerr("DESC",$$^MSG(1076,40))
 I '($P(vobj(this),$C(124),7)=""),'(+$P(vobj(this),$C(124),7)=$P(vobj(this),$C(124),7))  S $P(vobj(this),$C(124),7)=$$vRCtrimNumber($P(vobj(this),$C(124),7))
 S X=$P(vobj(this),$C(124),7) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXEFD",$$^MSG(742,"N"))
 I '($P(vobj(this),$C(124),14)=""),'(+$P(vobj(this),$C(124),14)=$P(vobj(this),$C(124),14))  S $P(vobj(this),$C(124),14)=$$vRCtrimNumber($P(vobj(this),$C(124),14))
 S X=$P(vobj(this),$C(124),14) I '(X=""),(X'?1.3N),(X'?1"-"1.2N) D vRCvalidateDDerr("MAXFT",$$^MSG(742,"N"))
 I '($P(vobj(this),$C(124),26)=""),'(+$P(vobj(this),$C(124),26)=$P(vobj(this),$C(124),26))  S $P(vobj(this),$C(124),26)=$$vRCtrimNumber($P(vobj(this),$C(124),26))
 S X=$P(vobj(this),$C(124),26) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXIN",$$^MSG(742,"N"))
 I '($P(vobj(this),$C(124),27)=""),'(+$P(vobj(this),$C(124),27)=$P(vobj(this),$C(124),27))  S $P(vobj(this),$C(124),27)=$$vRCtrimNumber($P(vobj(this),$C(124),27))
 S X=$P(vobj(this),$C(124),27) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXREV",$$^MSG(742,"N"))
 I '($P(vobj(this),$C(124),8)=""),'(+$P(vobj(this),$C(124),8)=$P(vobj(this),$C(124),8))  S $P(vobj(this),$C(124),8)=$$vRCtrimNumber($P(vobj(this),$C(124),8))
 S X=$P(vobj(this),$C(124),8) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXWO",$$^MSG(742,"N"))
 S X=$P(vobj(this),$C(124),2) I '(X=""),'($D(^SCATBL(0,X))#2) D vRCvalidateDDerr("MENU",$$^MSG(1485,X))
 I '(($P(vobj(this),$C(124),24)=1)!($P(vobj(this),$C(124),24)=0)) D vRCvalidateDDerr("MULPIN",$$^MSG(742,"L"))
 I '($P(vobj(this),$C(124),17)=""),'(+$P(vobj(this),$C(124),17)=$P(vobj(this),$C(124),17))  S $P(vobj(this),$C(124),17)=$$vRCtrimNumber($P(vobj(this),$C(124),17))
 S X=$P(vobj(this),$C(124),17) I '(X="") S errmsg=$$VAL^DBSVER("$",12,0,,,,,2) I '(errmsg="") D vRCvalidateDDerr("OACMAX",$$^MSG(979,"SCAU0.OACMAX"_" "_errmsg))
 I '($P(vobj(this),$C(124),18)=""),'(+$P(vobj(this),$C(124),18)=$P(vobj(this),$C(124),18))  S $P(vobj(this),$C(124),18)=$$vRCtrimNumber($P(vobj(this),$C(124),18))
 S X=$P(vobj(this),$C(124),18) I '(X="") S errmsg=$$VAL^DBSVER("$",12,0,,,,,2) I '(errmsg="") D vRCvalidateDDerr("OACMIN",$$^MSG(979,"SCAU0.OACMIN"_" "_errmsg))
 I '(($P(vobj(this),$C(124),10)=1)!($P(vobj(this),$C(124),10)=0)) D vRCvalidateDDerr("OVR",$$^MSG(742,"L"))
 I '($P(vobj(this),$C(124),15)=""),'(+$P(vobj(this),$C(124),15)=$P(vobj(this),$C(124),15))  S $P(vobj(this),$C(124),15)=$$vRCtrimNumber($P(vobj(this),$C(124),15))
 S X=$P(vobj(this),$C(124),15) I '(X=""),(X'?1.3N),(X'?1"-"1.2N) D vRCvalidateDDerr("OVRFT",$$^MSG(742,"N"))
 I '(($P(vobj(this),$C(124),23)=1)!($P(vobj(this),$C(124),23)=0)) D vRCvalidateDDerr("PINTRCK",$$^MSG(742,"L"))
 I '(($P(vobj(this),$C(124),28)=1)!($P(vobj(this),$C(124),28)=0)) D vRCvalidateDDerr("PLSAUPD",$$^MSG(742,"L"))
 I '($P(vobj(this),$C(124),4)=""),'(+$P(vobj(this),$C(124),4)=$P(vobj(this),$C(124),4))  S $P(vobj(this),$C(124),4)=$$vRCtrimNumber($P(vobj(this),$C(124),4))
 S X=$P(vobj(this),$C(124),4) I '(X=""),(X'?1.3N),(X'?1"-"1.2N) D vRCvalidateDDerr("PWDCHG",$$^MSG(742,"N"))
 I '($P(vobj(this),$C(124),3)=""),'(+$P(vobj(this),$C(124),3)=$P(vobj(this),$C(124),3))  S $P(vobj(this),$C(124),3)=$$vRCtrimNumber($P(vobj(this),$C(124),3))
 S X=$P(vobj(this),$C(124),3) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("PWDLEN",$$^MSG(742,"N"))
 I '($P(vobj(this),$C(124),5)=""),'(+$P(vobj(this),$C(124),5)=$P(vobj(this),$C(124),5))  S $P(vobj(this),$C(124),5)=$$vRCtrimNumber($P(vobj(this),$C(124),5))
 S X=$P(vobj(this),$C(124),5) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("PWDTRY",$$^MSG(742,"N"))
 I '(($P(vobj(this),$C(124),13)=1)!($P(vobj(this),$C(124),13)=0)) D vRCvalidateDDerr("RBRCC",$$^MSG(742,"L"))
 S X=$P(vobj(this),$C(124),25) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("RETTIME",$$^MSG(742,"C"))
 I '(($P(vobj(this),$C(124),9)=1)!($P(vobj(this),$C(124),9)=0)) D vRCvalidateDDerr("RSTRCT",$$^MSG(742,"L"))
 I '(($P(vobj(this),$C(124),6)=1)!($P(vobj(this),$C(124),6)=0)) D vRCvalidateDDerr("SECUCLS",$$^MSG(742,"L"))
 I '(($P(vobj(this),$C(124),22)=1)!($P(vobj(this),$C(124),22)=0)) D vRCvalidateDDerr("SESHIS",$$^MSG(742,"L"))
 Q 
 ;
vRCvalidateDD1(this) ; 
 N ER S ER=0
 N RM S RM=""
 N errmsg N X
 I ($D(vobj(this,-100,"1*","UCLS"))&($P($E($G(vobj(this,-100,"1*","UCLS")),5,9999),$C(124))'=vobj(this,-3))) I ($L(vobj(this,-3))>12) D vRCvalidateDDerr("UCLS",$$^MSG(1076,12))
 I ($D(vobj(this,-100,"0*","CCPOPT"))&($P($E($G(vobj(this,-100,"0*","CCPOPT")),5,9999),$C(124))'=$P(vobj(this),$C(124),19))) S X=$P(vobj(this),$C(124),19) I '(X=""),'$$vCaEx2() D vRCvalidateDDerr("CCPOPT",$$^MSG(1485,X))
 I ($D(vobj(this,-100,"0*","DEALEFD"))&($P($E($G(vobj(this,-100,"0*","DEALEFD")),5,9999),$C(124))'=$P(vobj(this),$C(124),16))) I '(($P(vobj(this),$C(124),16)=1)!($P(vobj(this),$C(124),16)=0)) D vRCvalidateDDerr("DEALEFD",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","DESC"))&($P($E($G(vobj(this,-100,"0*","DESC")),5,9999),$C(124))'=$P(vobj(this),$C(124),1))) I ($L($P(vobj(this),$C(124),1))>40) D vRCvalidateDDerr("DESC",$$^MSG(1076,40))
 I ($D(vobj(this,-100,"0*","MAXEFD"))&($P($E($G(vobj(this,-100,"0*","MAXEFD")),5,9999),$C(124))'=$P(vobj(this),$C(124),7))),'($P(vobj(this),$C(124),7)=""),'(+$P(vobj(this),$C(124),7)=$P(vobj(this),$C(124),7))  S $P(vobj(this),$C(124),7)=$$vRCtrimNumber($P(vobj(this),$C(124),7))
 I ($D(vobj(this,-100,"0*","MAXEFD"))&($P($E($G(vobj(this,-100,"0*","MAXEFD")),5,9999),$C(124))'=$P(vobj(this),$C(124),7))) S X=$P(vobj(this),$C(124),7) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXEFD",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","MAXFT"))&($P($E($G(vobj(this,-100,"0*","MAXFT")),5,9999),$C(124))'=$P(vobj(this),$C(124),14))),'($P(vobj(this),$C(124),14)=""),'(+$P(vobj(this),$C(124),14)=$P(vobj(this),$C(124),14))  S $P(vobj(this),$C(124),14)=$$vRCtrimNumber($P(vobj(this),$C(124),14))
 I ($D(vobj(this,-100,"0*","MAXFT"))&($P($E($G(vobj(this,-100,"0*","MAXFT")),5,9999),$C(124))'=$P(vobj(this),$C(124),14))) S X=$P(vobj(this),$C(124),14) I '(X=""),(X'?1.3N),(X'?1"-"1.2N) D vRCvalidateDDerr("MAXFT",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","MAXIN"))&($P($E($G(vobj(this,-100,"0*","MAXIN")),5,9999),$C(124))'=$P(vobj(this),$C(124),26))),'($P(vobj(this),$C(124),26)=""),'(+$P(vobj(this),$C(124),26)=$P(vobj(this),$C(124),26))  S $P(vobj(this),$C(124),26)=$$vRCtrimNumber($P(vobj(this),$C(124),26))
 I ($D(vobj(this,-100,"0*","MAXIN"))&($P($E($G(vobj(this,-100,"0*","MAXIN")),5,9999),$C(124))'=$P(vobj(this),$C(124),26))) S X=$P(vobj(this),$C(124),26) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXIN",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","MAXREV"))&($P($E($G(vobj(this,-100,"0*","MAXREV")),5,9999),$C(124))'=$P(vobj(this),$C(124),27))),'($P(vobj(this),$C(124),27)=""),'(+$P(vobj(this),$C(124),27)=$P(vobj(this),$C(124),27))  S $P(vobj(this),$C(124),27)=$$vRCtrimNumber($P(vobj(this),$C(124),27))
 I ($D(vobj(this,-100,"0*","MAXREV"))&($P($E($G(vobj(this,-100,"0*","MAXREV")),5,9999),$C(124))'=$P(vobj(this),$C(124),27))) S X=$P(vobj(this),$C(124),27) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXREV",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","MAXWO"))&($P($E($G(vobj(this,-100,"0*","MAXWO")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))),'($P(vobj(this),$C(124),8)=""),'(+$P(vobj(this),$C(124),8)=$P(vobj(this),$C(124),8))  S $P(vobj(this),$C(124),8)=$$vRCtrimNumber($P(vobj(this),$C(124),8))
 I ($D(vobj(this,-100,"0*","MAXWO"))&($P($E($G(vobj(this,-100,"0*","MAXWO")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))) S X=$P(vobj(this),$C(124),8) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("MAXWO",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","MENU"))&($P($E($G(vobj(this,-100,"0*","MENU")),5,9999),$C(124))'=$P(vobj(this),$C(124),2))) S X=$P(vobj(this),$C(124),2) I '(X=""),'($D(^SCATBL(0,X))#2) D vRCvalidateDDerr("MENU",$$^MSG(1485,X))
 I ($D(vobj(this,-100,"0*","MULPIN"))&($P($E($G(vobj(this,-100,"0*","MULPIN")),5,9999),$C(124))'=$P(vobj(this),$C(124),24))) I '(($P(vobj(this),$C(124),24)=1)!($P(vobj(this),$C(124),24)=0)) D vRCvalidateDDerr("MULPIN",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","OACMAX"))&($P($E($G(vobj(this,-100,"0*","OACMAX")),5,9999),$C(124))'=$P(vobj(this),$C(124),17))),'($P(vobj(this),$C(124),17)=""),'(+$P(vobj(this),$C(124),17)=$P(vobj(this),$C(124),17))  S $P(vobj(this),$C(124),17)=$$vRCtrimNumber($P(vobj(this),$C(124),17))
 I ($D(vobj(this,-100,"0*","OACMAX"))&($P($E($G(vobj(this,-100,"0*","OACMAX")),5,9999),$C(124))'=$P(vobj(this),$C(124),17))) S X=$P(vobj(this),$C(124),17) I '(X="") S errmsg=$$VAL^DBSVER("$",12,0,,,,,2) I '(errmsg="") D vRCvalidateDDerr("OACMAX",$$^MSG(979,"SCAU0.OACMAX"_" "_errmsg))
 I ($D(vobj(this,-100,"0*","OACMIN"))&($P($E($G(vobj(this,-100,"0*","OACMIN")),5,9999),$C(124))'=$P(vobj(this),$C(124),18))),'($P(vobj(this),$C(124),18)=""),'(+$P(vobj(this),$C(124),18)=$P(vobj(this),$C(124),18))  S $P(vobj(this),$C(124),18)=$$vRCtrimNumber($P(vobj(this),$C(124),18))
 I ($D(vobj(this,-100,"0*","OACMIN"))&($P($E($G(vobj(this,-100,"0*","OACMIN")),5,9999),$C(124))'=$P(vobj(this),$C(124),18))) S X=$P(vobj(this),$C(124),18) I '(X="") S errmsg=$$VAL^DBSVER("$",12,0,,,,,2) I '(errmsg="") D vRCvalidateDDerr("OACMIN",$$^MSG(979,"SCAU0.OACMIN"_" "_errmsg))
 I ($D(vobj(this,-100,"0*","OVR"))&($P($E($G(vobj(this,-100,"0*","OVR")),5,9999),$C(124))'=$P(vobj(this),$C(124),10))) I '(($P(vobj(this),$C(124),10)=1)!($P(vobj(this),$C(124),10)=0)) D vRCvalidateDDerr("OVR",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","OVRFT"))&($P($E($G(vobj(this,-100,"0*","OVRFT")),5,9999),$C(124))'=$P(vobj(this),$C(124),15))),'($P(vobj(this),$C(124),15)=""),'(+$P(vobj(this),$C(124),15)=$P(vobj(this),$C(124),15))  S $P(vobj(this),$C(124),15)=$$vRCtrimNumber($P(vobj(this),$C(124),15))
 I ($D(vobj(this,-100,"0*","OVRFT"))&($P($E($G(vobj(this,-100,"0*","OVRFT")),5,9999),$C(124))'=$P(vobj(this),$C(124),15))) S X=$P(vobj(this),$C(124),15) I '(X=""),(X'?1.3N),(X'?1"-"1.2N) D vRCvalidateDDerr("OVRFT",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","PINTRCK"))&($P($E($G(vobj(this,-100,"0*","PINTRCK")),5,9999),$C(124))'=$P(vobj(this),$C(124),23))) I '(($P(vobj(this),$C(124),23)=1)!($P(vobj(this),$C(124),23)=0)) D vRCvalidateDDerr("PINTRCK",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","PLSAUPD"))&($P($E($G(vobj(this,-100,"0*","PLSAUPD")),5,9999),$C(124))'=$P(vobj(this),$C(124),28))) I '(($P(vobj(this),$C(124),28)=1)!($P(vobj(this),$C(124),28)=0)) D vRCvalidateDDerr("PLSAUPD",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","PWDCHG"))&($P($E($G(vobj(this,-100,"0*","PWDCHG")),5,9999),$C(124))'=$P(vobj(this),$C(124),4))),'($P(vobj(this),$C(124),4)=""),'(+$P(vobj(this),$C(124),4)=$P(vobj(this),$C(124),4))  S $P(vobj(this),$C(124),4)=$$vRCtrimNumber($P(vobj(this),$C(124),4))
 I ($D(vobj(this,-100,"0*","PWDCHG"))&($P($E($G(vobj(this,-100,"0*","PWDCHG")),5,9999),$C(124))'=$P(vobj(this),$C(124),4))) S X=$P(vobj(this),$C(124),4) I '(X=""),(X'?1.3N),(X'?1"-"1.2N) D vRCvalidateDDerr("PWDCHG",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","PWDLEN"))&($P($E($G(vobj(this,-100,"0*","PWDLEN")),5,9999),$C(124))'=$P(vobj(this),$C(124),3))),'($P(vobj(this),$C(124),3)=""),'(+$P(vobj(this),$C(124),3)=$P(vobj(this),$C(124),3))  S $P(vobj(this),$C(124),3)=$$vRCtrimNumber($P(vobj(this),$C(124),3))
 I ($D(vobj(this,-100,"0*","PWDLEN"))&($P($E($G(vobj(this,-100,"0*","PWDLEN")),5,9999),$C(124))'=$P(vobj(this),$C(124),3))) S X=$P(vobj(this),$C(124),3) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("PWDLEN",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","PWDTRY"))&($P($E($G(vobj(this,-100,"0*","PWDTRY")),5,9999),$C(124))'=$P(vobj(this),$C(124),5))),'($P(vobj(this),$C(124),5)=""),'(+$P(vobj(this),$C(124),5)=$P(vobj(this),$C(124),5))  S $P(vobj(this),$C(124),5)=$$vRCtrimNumber($P(vobj(this),$C(124),5))
 I ($D(vobj(this,-100,"0*","PWDTRY"))&($P($E($G(vobj(this,-100,"0*","PWDTRY")),5,9999),$C(124))'=$P(vobj(this),$C(124),5))) S X=$P(vobj(this),$C(124),5) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("PWDTRY",$$^MSG(742,"N"))
 I ($D(vobj(this,-100,"0*","RBRCC"))&($P($E($G(vobj(this,-100,"0*","RBRCC")),5,9999),$C(124))'=$P(vobj(this),$C(124),13))) I '(($P(vobj(this),$C(124),13)=1)!($P(vobj(this),$C(124),13)=0)) D vRCvalidateDDerr("RBRCC",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","RETTIME"))&($P($E($G(vobj(this,-100,"0*","RETTIME")),5,9999),$C(124))'=$P(vobj(this),$C(124),25))) S X=$P(vobj(this),$C(124),25) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("RETTIME",$$^MSG(742,"C"))
 I ($D(vobj(this,-100,"0*","RSTRCT"))&($P($E($G(vobj(this,-100,"0*","RSTRCT")),5,9999),$C(124))'=$P(vobj(this),$C(124),9))) I '(($P(vobj(this),$C(124),9)=1)!($P(vobj(this),$C(124),9)=0)) D vRCvalidateDDerr("RSTRCT",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","SECUCLS"))&($P($E($G(vobj(this,-100,"0*","SECUCLS")),5,9999),$C(124))'=$P(vobj(this),$C(124),6))) I '(($P(vobj(this),$C(124),6)=1)!($P(vobj(this),$C(124),6)=0)) D vRCvalidateDDerr("SECUCLS",$$^MSG(742,"L"))
 I ($D(vobj(this,-100,"0*","SESHIS"))&($P($E($G(vobj(this,-100,"0*","SESHIS")),5,9999),$C(124))'=$P(vobj(this),$C(124),22))) I '(($P(vobj(this),$C(124),22)=1)!($P(vobj(this),$C(124),22)=0)) D vRCvalidateDDerr("SESHIS",$$^MSG(742,"L"))
 Q 
 ;
vRCvalidateDDerr(column,errmsg) ; 
 N ER S ER=0
 N RM S RM=""
 D SETERR^DBSEXECU("SCAU0","MSG",979,"SCAU0."_column_" "_errmsg)
 I ER D throwError($get(RM))
 Q 
 ;
vRCtrimNumber(str) ; 
 I ($E(str,1)="0") S str=$$vStrTrim(str,-1,"0") I (str="") S str="0"
 I (str["."),($E(str,$L(str))="0") S str=$$RTCHR^%ZFUNC(str,"0") I ($E(str,$L(str))=".") S str=$E(str,1,$L(str)-1) I (str="") S str="0"
 Q str
 ;
vRCkeyChanged(this,vRCparams,vRCaudit) ; 
 N vTp
 N newkeys N oldkeys N vRCauditIns
 N newKey1 S newKey1=vobj(this,-3)
 N oldKey1 S oldKey1=$S($D(vobj(this,-100,"1*","UCLS")):$P($E(vobj(this,-100,"1*","UCLS"),5,9999),$C(124)),1:vobj(this,-3))
  N V1 S V1=vobj(this,-3) I ($D(^SCAU(0,V1))#2) D throwError($$^MSG(2327))
 S newkeys=newKey1
 S oldkeys=oldKey1
  S vobj(this,-3)=oldKey1
 S vRCparams=$$setPar^UCUTILN(vRCparams,"NOINDEX")
 I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,1)
 D vRCmiscValidations(this,vRCparams,1)
 D vRCupdateDB(this,1,vRCparams,.vRCaudit,.vRCauditIns)
  S vobj(this,-3)=newKey1
 N newrec S newrec=$$vReCp1(this)
 S vobj(newrec,-2)=0
 S vTp=($TL=0) TS:vTp (vobj):transactionid="CS" D vSave^RecordSCAU0(newrec,$$initPar^UCUTILN($$initPar^UCUTILN("/NOVAL/NOCASDEL/NOJOURNAL/NOTRIGBEF/NOTRIGAFT/"))) K vobj(newrec,-100) S vobj(newrec,-2)=1 TC:vTp  
 D
 .	N %O S %O=1
 .	N ER S ER=0
 .	N RM S RM=""
 .	;   #ACCEPT Date=10/24/2008; Pgm=RussellDS; CR=30801; Group=ACCESS
 .	D CASUPD^DBSEXECU("SCAU0",oldkeys,newkeys)
 .	I ER D throwError($get(RM))
 .	Q 
  S vobj(this,-3)=oldKey1
 S vRCparams=$$initPar^UCUTILN("/NOVAL/NOCASDEL/NOJOURNAL/NOTRIGBEF/NOTRIGAFT/")
 D vRCdelete(this,vRCparams,.vRCaudit,1)
  S vobj(this,-3)=newKey1
 K vobj(+$G(newrec)) Q 
 ;
throwError(MSG) ; 
 S $ZE="0,"_$ZPOS_","_"%PSL-E-DBFILER,"_$translate(MSG,",","~"),$EC=",U1001,"
 Q 
 ; ----------------
 ;  #OPTION ResultClass 1
vStrRep(object,p1,p2,p3,p4,qt) ; String.replace
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 ;
 I p3<0 Q object
 I $L(p1)=1,$L(p2)<2,'p3,'p4,(qt="") Q $translate(object,p1,p2)
 ;
 N y S y=0
 F  S y=$$vStrFnd(object,p1,y,p4,qt) Q:y=0  D
 .	S object=$E(object,1,y-$L(p1)-1)_p2_$E(object,y,1048575)
 .	S y=y+$L(p2)-$L(p1)
 .	I p3 S p3=p3-1 I p3=0 S y=$L(object)+1
 .	Q 
 Q object
 ; ----------------
 ;  #OPTION ResultClass 1
vCaEx1() ; {Cache}%CACHE("STBLCCPOPT").isDefined("STBLCCPOPT","CCPOPT=:X")
 N vret
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 N vRec,vop1 S vRec=$$vCa2(X,.vop1)
 S vret=$G(vop1)=1 Q vret
 ; ----------------
 ;  #OPTION ResultClass 1
vCaEx2() ; {Cache}%CACHE("STBLCCPOPT").isDefined("STBLCCPOPT","CCPOPT=:X")
 N vret
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 N vRec,vop1 S vRec=$$vCa2(X,.vop1)
 S vret=$G(vop1)=1 Q vret
 ; ----------------
 ;  #OPTION ResultClass 1
vStrTrim(object,p1,p2) ; String.trim
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 I p1'<0 S object=$$RTCHR^%ZFUNC(object,p2)
 I p1'>0 F  Q:$E(object,1)'=p2  S object=$E(object,2,1048575)
 Q object
 ; ----------------
 ;  #OPTION ResultClass 1
vStrFnd(object,p1,p2,p3,qt) ; String.find
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 ;
 I (p1="") Q $S(p2<1:1,1:+p2)
 I p3 S object=$ZCONVERT(object,"U") S p1=$ZCONVERT(p1,"U")
 S p2=$F(object,p1,p2)
 I '(qt=""),$L($E(object,1,p2-1),qt)#2=0 D
 .	F  S p2=$F(object,p1,p2) Q:p2=0!($L($E(object,1,p2-1),qt)#2) 
 .	Q 
 Q p2
 ;
vCa2(v1,v2out) ; voXN = ({Cache}%CACHE("STBLCCPOPT").getRecord(STBLCCPOPT,1)
 ;
 I '$D(%CACHE("STBLCCPOPT",v1)) D
 .  I $G(%CACHE("STBLCCPOPT"))>100 KILL %CACHE("STBLCCPOPT")
 .  S %CACHE("STBLCCPOPT")=$G(%CACHE("STBLCCPOPT"))+1
 .  S %CACHE("STBLCCPOPT",v1)=$$vRCgetRecord1Opt^RecordSTBLCCPOPT(v1,0,.v2out),%CACHE("STBLCCPOPT",v1,-2)=v2out
 ;
 ;
 E  S v2out=%CACHE("STBLCCPOPT",v1,-2)
 Q %CACHE("STBLCCPOPT",v1)
 ;
vReCp1(v1) ; RecordSCAU0.copy: SCAU0
 ;
 Q $$copy^UCGMR(this)
