 ; 
 ; **** Routine compiled from DATA-QWIK Filer RecordDBSMDD ****
 ; 
 ; 01/23/2016 18:58 - kulhan
 ; 
 ;
 ; Record Class code for table DBSMDD
 ;
 ; Generated by PSLRecordBuilder on 01/23/2016 at 18:58 by 1
 ;
