 ; 
 ; **** Routine compiled from DATA-QWIK Filer RecordCRCD ****
 ; 
 ; 02/24/2010 18:38 - pip
 ; 
 ;
 ; Record Class code for table CRCD
 ;
 ; Generated by PSLRecordBuilder on 02/24/2010 at 18:38 by
 ;
vcdmNew() ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordCRCD",vobj(vOid,-2)=0,vobj(vOid)=""
 S vobj(vOid,-3)=""
 S vobj(vOid,-4)=""
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord0(v1,v2,vfromDbSet) ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordCRCD"
 S vobj(vOid)=$G(^CRCD(v1,v2))
 I vobj(vOid)="",'$D(^CRCD(v1,v2))
 S vobj(vOid,-2)=1
 I $T K vobj(vOid) S $ZE="0,"_$ZPOS_",%PSL-E-RECNOFL,,CRCD",$EC=",U1001,"
 S vobj(vOid,-3)=v1
 S vobj(vOid,-4)=v2
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord1(v1,v2,vfromDbSet) ; 
 N vOid
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S vOid=$O(vobj(""),-1)+1,vobj(vOid,-1)="RecordCRCD"
 S vobj(vOid)=$G(^CRCD(v1,v2))
 I vobj(vOid)="",'$D(^CRCD(v1,v2))
 S vobj(vOid,-2)='$T
 S vobj(vOid,-3)=v1
 S vobj(vOid,-4)=v2
 ;*** End of code by-passed by compiler ***
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=SCOPE
 Q vOid
 ;
vRCgetRecord0Opt(v1,v2,vfromDbSet,v2out) ; 
 N crcd
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S crcd=$G(^CRCD(v1,v2))
 I crcd="",'$D(^CRCD(v1,v2))
 S v2out=1
 I $T S $ZE="0,"_$ZPOS_",%PSL-E-RECNOFL,,CRCD",$EC=",U1001,"
 ;*** End of code by-passed by compiler ***
 Q crcd
 ;
vRCgetRecord1Opt(v1,v2,vfromDbSet,v2out) ; 
 N crcd
 ;  #ACCEPT DATE=02/26/2008; PGM=Dan Russell; CR=30801; Group=BYPASS
 ;*** Start of code by-passed by compiler
 S crcd=$G(^CRCD(v1,v2))
 I crcd="",'$D(^CRCD(v1,v2))
 S v2out='$T
 ;*** End of code by-passed by compiler ***
 Q crcd
 ;
vBypassSave(this) ; 
 D vSave(this,"/NOJOURNAL/NOTRIGAFT/NOTRIGBEF/NOVALDD/NOVALREQ/NOVALRI/NOVALST",0)
 Q 
 ;
vSave(this,vRCparams,vauditLogSeq) ; 
 N vRCaudit N vRCauditIns
 N %O S %O=$G(vobj(this,-2))
 I ($get(vRCparams)="") S vRCparams="/CASDEL/INDEX/JOURNAL/LOG/TRIGAFT/TRIGBEF/UPDATE/VALDD/VALFK/VALREQ/VALRI/VALST/"
 I (%O=0) D
 .	D AUDIT^UCUTILN(this,.vRCauditIns,11,"|")
 .	D vRCsetDefaults(this)
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,%O)
 .	D vRCmiscValidations(this,vRCparams,%O)
 .	D vRCupdateDB(this,%O,vRCparams,.vRCaudit,.vRCauditIns)
 .	Q 
 E  I (%O=1) D
 .	Q:'$D(vobj(this,-100)) 
 .	D AUDIT^UCUTILN(this,.vRCaudit,11,"|")
 .	I ($D(vobj(this,-100,"1*","CO"))&($P($E($G(vobj(this,-100,"1*","CO")),5,9999),$C(124))'=vobj(this,-3)))!($D(vobj(this,-100,"2*","CRCD"))&($P($E($G(vobj(this,-100,"2*","CRCD")),5,9999),$C(124))'=vobj(this,-4))) D vRCkeyChanged(this,vRCparams,.vRCaudit) Q 
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForUpdate(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD1(this)
 .	D vRCmiscValidations(this,vRCparams,%O)
 .	D vRCupdateDB(this,%O,vRCparams,.vRCaudit,.vRCauditIns)
 .	Q 
 E  I (%O=2) D
 .	I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 .	I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,%O)
 .	D vRCmiscValidations(this,vRCparams,2)
 .	Q 
 E  I (%O=3) D
 .	  N V1,V2 S V1=vobj(this,-3),V2=vobj(this,-4) Q:'($D(^CRCD(V1,V2))) 
 .	D vRCdelete(this,vRCparams,.vRCaudit,0)
 .	Q 
 Q 
 ;
vcheckAccessRights() ; 
 Q ""
 ;
vinsertAccess(userclass) ; 
 Q 1
 ;
vinsertOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vupdateAccess(userclass) ; 
 Q 1
 ;
vupdateOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vdeleteAccess(userclass) ; 
 Q 1
 ;
vdeleteOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vselectAccess(userclass,restrict,from) ; 
 S (restrict,from)=""
 Q 1
 ;
vselectOK(this,userclass) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vselectOptmOK(userclass,crcd,vkey1,vkey2) ; PUBLIC access is allowed, no restrict clause
 Q 1
 ;
vgetLogging() ; 
 Q "0"
 ;
logUserclass(operation) ; 
 I (operation="INSERT") Q 0
 E  I (operation="UPDATE") Q 0
 E  I (operation="DELETE") Q 0
 E  I (operation="SELECT") Q 0
 Q 0
 ;
vlogSelect(statement,using) ; 
 Q 0
 ;
columnList() ; 
 N columns S columns=""
 S columns=columns_"AVESPOTACCUM,BUY,CALENDAR,CASHCUR,CHKDESC,CNTRY,CO,COACC,CONV,CRCD,CRCDNO,CURDEC,DESC,DLM,EMU,EMUTED,EMUTSD,EXCH,FINSPOT,FNCRATE,"
 S columns=columns_"FXVAR,INTPMT,MAXRATE,MIDRATE,MINCASH,MINRATE,NOSTROFX,OFFBID,OFFOFFER,OTCBID,OTCOFFER,OURPREF,POACC,RATDEC,RETAIL,SELL,SPOTBID,SPOTOFFER,SPTDYS,SYSCEQ,"
 S columns=columns_"TERMS,TLM,VARIANCE,"
 Q $$vStrRep("AVESPOTACCUM,BUY,CALENDAR,CASHCUR,CHKDESC,CNTRY,CO,COACC,CONV,CRCD,CRCDNO,CURDEC,DESC,DLM,EMU,EMUTED,EMUTSD,EXCH,FINSPOT,FNCRATE,FXVAR,INTPMT,MAXRATE,MIDRATE,MINCASH,MINRATE,NOSTROFX,OFFBID,OFFOFFER,OTCBID,OTCOFFER,OURPREF,POACC,RATDEC,RETAIL,SELL,SPOTBID,SPOTOFFER,SPTDYS,SYSCEQ,TERMS,TLM,VARIANCE",",",$char(9),0,0,"")
 ;
columnListBM() ; 
 Q ""
 ;
columnListCMP() ; 
 Q $$vStrRep("",",",$char(9),0,0,"")
 ;
getColumnMap(map) ; 
 ;
 S map(-4)="CRCD:T:"
 S map(-3)="CO:T:"
 S map(-1)="BUY:L:4;CALENDAR:T:10;CASHCUR:L:11;CHKDESC:T:15;CNTRY:T:9;COACC:L:20;CONV:L:21;CRCDNO:T:2;CURDEC:N:7;DESC:T:1;EMU:L:56;EMUTED:D:59;EMUTSD:D:58;EXCH:N:53;FNCRATE:N:57;FXVAR:N:45;INTPMT:L:40;MAXRATE:N:1"
 S map(-1)=map(-1)_"4;MINCASH:$:18;MINRATE:N:13;NOSTROFX:N:46;OURPREF:N:37;POACC:L:19;RATDEC:N:8;RETAIL:L:3;SELL:L:5;SPTDYS:N:36;SYSCEQ:L:16;VARIANCE:N:6"
 S map(1)="AVESPOTACCUM:N:9;DLM:D:11;FINSPOT:N:8;MIDRATE:N:1;OFFBID:N:6;OFFOFFER:N:7;OTCBID:N:4;OTCOFFER:N:5;SPOTBID:N:2;SPOTOFFER:N:3;TERMS:L:10;TLM:C:12"
 Q 
 ;
vlegacy(processMode,params) ; 
 N vTp
 I (processMode=2) D
 .	N crcd S crcd=$$vRCgetRecord0^RecordCRCD(CO,CRCD,0)
 .	S vobj(crcd,-2)=2
 . S vTp=($TL=0) TS:vTp (vobj):transactionid="CS" D vSave^RecordCRCD(crcd,$$initPar^UCUTILN(params)) K vobj(crcd,-100) S vobj(crcd,-2)=1 TC:vTp  
 .	K vobj(+$G(crcd)) Q 
 Q 
 ;
vhasLiterals() ; 
 Q 0
 ;
vRCmiscValidations(this,vRCparams,processMode) ; 
 I (("/"_vRCparams_"/")["/VALST/")  N V1,V2 S V1=vobj(this,-3),V2=vobj(this,-4) I '(''($D(^CRCD(V1,V2)))=''processMode) D
 .	N errmsg
 .	I (+processMode'=+0) S errmsg=$$^MSG(7932)
 .	E  S errmsg=$$^MSG(2327)
 .	D throwError(errmsg)
 .	Q 
 Q 
 ;
vRCupdateDB(this,processMode,vRCparams,vRCaudit,vRCauditIns) ; 
 I '(("/"_vRCparams_"/")["/NOUPDATE/") D
 .	I '(("/"_vRCparams_"/")["/NOLOG/") D
 ..		I (processMode=1) D ^DBSLOGIT(this,1,.vRCaudit) Q 
 ..		D ^DBSLOGIT(this,0,.vRCauditIns)
 ..		Q 
 .	N n
 .	S n=-1
 .	F  S n=$order(vobj(this,n)) Q:(n="")  D
 ..		Q:'($D(vobj(this,n))#2) 
 ..		;    #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; GROUP=BYPASS
 ..		;*** Start of code by-passed by compiler
 ..		S ^CRCD(vobj(this,-3),vobj(this,-4),n)=vobj(this,n)
 ..		;*** End of code by-passed by compiler ***
 ..		Q 
 .	;   #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; GROUP=BYPASS
 .	;*** Start of code by-passed by compiler
 .	if $D(vobj(this)) S ^CRCD(vobj(this,-3),vobj(this,-4))=vobj(this)
 .	;*** End of code by-passed by compiler ***
 .	Q 
 Q 
 ;
vRCdelete(this,vRCparams,vRCaudit,isKeyChange) ; 
 I '$get(isKeyChange),$D(vobj(this,-100)) D throwError("Deleted object cannot be modified")
 I '(("/"_vRCparams_"/")["/NOLOG/") D ^DBSLOGIT(this,3)
 ;  #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; Group=BYPASS
 ;*** Start of code by-passed by compiler
 kill ^CRCD(vobj(this,-3),vobj(this,-4))
 ;*** End of code by-passed by compiler ***
 Q 
 ;
vRCsetDefaults(this) ; 
  S:'$D(vobj(this,1)) vobj(this,1)=$S(vobj(this,-2):$G(^CRCD(vobj(this,-3),vobj(this,-4),1)),1:"")
 I ($P(vobj(this),$C(124),4)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),4)=0
 I ($P(vobj(this),$C(124),11)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),11)=0
 I ($P(vobj(this),$C(124),20)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),20)=0
 I ($P(vobj(this),$C(124),21)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),21)=0
 I ($P(vobj(this),$C(124),56)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),56)=0
 I ($P(vobj(this),$C(124),40)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),40)=0
 I ($P(vobj(this),$C(124),19)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),19)=0
 I ($P(vobj(this),$C(124),3)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),3)=1
 I ($P(vobj(this),$C(124),5)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),5)=0
 I ($P(vobj(this),$C(124),16)="")  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),16)=0
 I ($P(vobj(this,1),$C(124),10)="")  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),10)=0
 Q 
 ;
vRCchkReqForInsert(this) ; 
  S:'$D(vobj(this,1)) vobj(this,1)=$S(vobj(this,-2):$G(^CRCD(vobj(this,-3),vobj(this,-4),1)),1:"")
 I ($P(vobj(this),$C(124),4)="") D vRCrequiredErr("BUY")
 I ($P(vobj(this),$C(124),11)="") D vRCrequiredErr("CASHCUR")
 I ($P(vobj(this),$C(124),15)="") D vRCrequiredErr("CHKDESC")
 I ($P(vobj(this),$C(124),9)="") D vRCrequiredErr("CNTRY")
 I (vobj(this,-3)="") D vRCrequiredErr("CO")
 I ($P(vobj(this),$C(124),20)="") D vRCrequiredErr("COACC")
 I ($P(vobj(this),$C(124),21)="") D vRCrequiredErr("CONV")
 I (vobj(this,-4)="") D vRCrequiredErr("CRCD")
 I ($P(vobj(this),$C(124),2)="") D vRCrequiredErr("CRCDNO")
 I ($P(vobj(this),$C(124),7)="") D vRCrequiredErr("CURDEC")
 I ($P(vobj(this),$C(124),1)="") D vRCrequiredErr("DESC")
 I ($P(vobj(this),$C(124),56)="") D vRCrequiredErr("EMU")
 I ($P(vobj(this),$C(124),40)="") D vRCrequiredErr("INTPMT")
 I ($P(vobj(this),$C(124),14)="") D vRCrequiredErr("MAXRATE")
 I ($P(vobj(this),$C(124),13)="") D vRCrequiredErr("MINRATE")
 I ($P(vobj(this),$C(124),19)="") D vRCrequiredErr("POACC")
 I ($P(vobj(this),$C(124),8)="") D vRCrequiredErr("RATDEC")
 I ($P(vobj(this),$C(124),3)="") D vRCrequiredErr("RETAIL")
 I ($P(vobj(this),$C(124),5)="") D vRCrequiredErr("SELL")
 I ($P(vobj(this),$C(124),36)="") D vRCrequiredErr("SPTDYS")
 I ($P(vobj(this),$C(124),16)="") D vRCrequiredErr("SYSCEQ")
 I ($P(vobj(this,1),$C(124),10)="") D vRCrequiredErr("TERMS")
 Q 
 ;
vRCchkReqForUpdate(this) ; 
  S:'$D(vobj(this,1)) vobj(this,1)=$S(vobj(this,-2):$G(^CRCD(vobj(this,-3),vobj(this,-4),1)),1:"")
 I (vobj(this,-3)="") D vRCrequiredErr("CO")
 I (vobj(this,-4)="") D vRCrequiredErr("CRCD")
 ; Node 1 - only one required column
 I ($D(vobj(this,-100,1,"TERMS"))&($P($E($G(vobj(this,-100,1,"TERMS")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),10))),($P(vobj(this,1),$C(124),10)="") D vRCrequiredErr("TERMS")
 I ($D(vobj(this,-100,"0*"))>9) D
 .	I ($D(vobj(this,-100,"0*","DESC"))&($P($E($G(vobj(this,-100,"0*","DESC")),5,9999),$C(124))'=$P(vobj(this),$C(124),1))),($P(vobj(this),$C(124),1)="") D vRCrequiredErr("DESC")
 .	I ($D(vobj(this,-100,"0*","CRCDNO"))&($P($E($G(vobj(this,-100,"0*","CRCDNO")),5,9999),$C(124))'=$P(vobj(this),$C(124),2))),($P(vobj(this),$C(124),2)="") D vRCrequiredErr("CRCDNO")
 .	I ($D(vobj(this,-100,"0*","RETAIL"))&($P($E($G(vobj(this,-100,"0*","RETAIL")),5,9999),$C(124))'=$P(vobj(this),$C(124),3))),($P(vobj(this),$C(124),3)="") D vRCrequiredErr("RETAIL")
 .	I ($D(vobj(this,-100,"0*","BUY"))&($P($E($G(vobj(this,-100,"0*","BUY")),5,9999),$C(124))'=$P(vobj(this),$C(124),4))),($P(vobj(this),$C(124),4)="") D vRCrequiredErr("BUY")
 .	I ($D(vobj(this,-100,"0*","SELL"))&($P($E($G(vobj(this,-100,"0*","SELL")),5,9999),$C(124))'=$P(vobj(this),$C(124),5))),($P(vobj(this),$C(124),5)="") D vRCrequiredErr("SELL")
 .	I ($D(vobj(this,-100,"0*","CURDEC"))&($P($E($G(vobj(this,-100,"0*","CURDEC")),5,9999),$C(124))'=$P(vobj(this),$C(124),7))),($P(vobj(this),$C(124),7)="") D vRCrequiredErr("CURDEC")
 .	I ($D(vobj(this,-100,"0*","RATDEC"))&($P($E($G(vobj(this,-100,"0*","RATDEC")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))),($P(vobj(this),$C(124),8)="") D vRCrequiredErr("RATDEC")
 .	I ($D(vobj(this,-100,"0*","CNTRY"))&($P($E($G(vobj(this,-100,"0*","CNTRY")),5,9999),$C(124))'=$P(vobj(this),$C(124),9))),($P(vobj(this),$C(124),9)="") D vRCrequiredErr("CNTRY")
 .	I ($D(vobj(this,-100,"0*","CASHCUR"))&($P($E($G(vobj(this,-100,"0*","CASHCUR")),5,9999),$C(124))'=$P(vobj(this),$C(124),11))),($P(vobj(this),$C(124),11)="") D vRCrequiredErr("CASHCUR")
 .	I ($D(vobj(this,-100,"0*","MINRATE"))&($P($E($G(vobj(this,-100,"0*","MINRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),13))),($P(vobj(this),$C(124),13)="") D vRCrequiredErr("MINRATE")
 .	I ($D(vobj(this,-100,"0*","MAXRATE"))&($P($E($G(vobj(this,-100,"0*","MAXRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),14))),($P(vobj(this),$C(124),14)="") D vRCrequiredErr("MAXRATE")
 .	I ($D(vobj(this,-100,"0*","CHKDESC"))&($P($E($G(vobj(this,-100,"0*","CHKDESC")),5,9999),$C(124))'=$P(vobj(this),$C(124),15))),($P(vobj(this),$C(124),15)="") D vRCrequiredErr("CHKDESC")
 .	I ($D(vobj(this,-100,"0*","SYSCEQ"))&($P($E($G(vobj(this,-100,"0*","SYSCEQ")),5,9999),$C(124))'=$P(vobj(this),$C(124),16))),($P(vobj(this),$C(124),16)="") D vRCrequiredErr("SYSCEQ")
 .	I ($D(vobj(this,-100,"0*","POACC"))&($P($E($G(vobj(this,-100,"0*","POACC")),5,9999),$C(124))'=$P(vobj(this),$C(124),19))),($P(vobj(this),$C(124),19)="") D vRCrequiredErr("POACC")
 .	I ($D(vobj(this,-100,"0*","COACC"))&($P($E($G(vobj(this,-100,"0*","COACC")),5,9999),$C(124))'=$P(vobj(this),$C(124),20))),($P(vobj(this),$C(124),20)="") D vRCrequiredErr("COACC")
 .	I ($D(vobj(this,-100,"0*","CONV"))&($P($E($G(vobj(this,-100,"0*","CONV")),5,9999),$C(124))'=$P(vobj(this),$C(124),21))),($P(vobj(this),$C(124),21)="") D vRCrequiredErr("CONV")
 .	I ($D(vobj(this,-100,"0*","SPTDYS"))&($P($E($G(vobj(this,-100,"0*","SPTDYS")),5,9999),$C(124))'=$P(vobj(this),$C(124),36))),($P(vobj(this),$C(124),36)="") D vRCrequiredErr("SPTDYS")
 .	I ($D(vobj(this,-100,"0*","INTPMT"))&($P($E($G(vobj(this,-100,"0*","INTPMT")),5,9999),$C(124))'=$P(vobj(this),$C(124),40))),($P(vobj(this),$C(124),40)="") D vRCrequiredErr("INTPMT")
 .	I ($D(vobj(this,-100,"0*","EMU"))&($P($E($G(vobj(this,-100,"0*","EMU")),5,9999),$C(124))'=$P(vobj(this),$C(124),56))),($P(vobj(this),$C(124),56)="") D vRCrequiredErr("EMU")
 .	Q 
 ; Node "1*" - only one required column
 I ($D(vobj(this,-100,"1*","CO"))&($P($E($G(vobj(this,-100,"1*","CO")),5,9999),$C(124))'=vobj(this,-3))),(vobj(this,-3)="") D vRCrequiredErr("CO")
 ; Node "2*" - only one required column
 I ($D(vobj(this,-100,"2*","CRCD"))&($P($E($G(vobj(this,-100,"2*","CRCD")),5,9999),$C(124))'=vobj(this,-4))),(vobj(this,-4)="") D vRCrequiredErr("CRCD")
 Q 
 ;
vRCrequiredErr(column) ; 
 N ER S ER=0
 N RM S RM=""
 D SETERR^DBSEXECU("CRCD","MSG",1767,"CRCD."_column)
 I ER D throwError($get(RM))
 Q 
 ;
vRCforceLoad(this) ; 
 N n S n=""
 ;  #ACCEPT DATE=04/22/04; PGM=Dan Russell; CR=20602; Group=BYPASS
 ;*** Start of code by-passed by compiler
 for  set n=$order(^CRCD(vobj(this,-3),vobj(this,-4),n)) quit:n=""  if '$D(vobj(this,n)),$D(^CRCD(vobj(this,-3),vobj(this,-4),n))#2 set vobj(this,n)=^(n)
 ;*** End of code by-passed by compiler ***
 Q 
 ;
vRCvalidateDD(this,processMode) ; 
 N ER S ER=0
 N RM S RM=""
 N errmsg N X
 I (processMode=2) D vRCforceLoad(this)
 I ($D(vobj(this,1))#2) D
 .	 S:'$D(vobj(this,1)) vobj(this,1)=$S(vobj(this,-2):$G(^CRCD(vobj(this,-3),vobj(this,-4),1)),1:"")
 .	I '($P(vobj(this,1),$C(124),9)=""),'(+$P(vobj(this,1),$C(124),9)=$P(vobj(this,1),$C(124),9))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),9)=$$vRCtrimNumber($P(vobj(this,1),$C(124),9))
 .	S X=$P(vobj(this,1),$C(124),9) I '(X="") S errmsg=$$VAL^DBSVER("N",10,,,,,,5) I '(errmsg="") D vRCvalidateDDerr("AVESPOTACCUM",$$^MSG(979,"CRCD.AVESPOTACCUM"_" "_errmsg))
 .	S X=$P(vobj(this,1),$C(124),11) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("DLM",$$^MSG(742,"D"))
 .	I '($P(vobj(this,1),$C(124),8)=""),'(+$P(vobj(this,1),$C(124),8)=$P(vobj(this,1),$C(124),8))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),8)=$$vRCtrimNumber($P(vobj(this,1),$C(124),8))
 .	S X=$P(vobj(this,1),$C(124),8) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("FINSPOT",$$^MSG(979,"CRCD.FINSPOT"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),1)=""),'(+$P(vobj(this,1),$C(124),1)=$P(vobj(this,1),$C(124),1))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),1)=$$vRCtrimNumber($P(vobj(this,1),$C(124),1))
 .	S X=$P(vobj(this,1),$C(124),1) I '(X="") S errmsg=$$VAL^DBSVER("N",13,0,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("MIDRATE",$$^MSG(979,"CRCD.MIDRATE"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),6)=""),'(+$P(vobj(this,1),$C(124),6)=$P(vobj(this,1),$C(124),6))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),6)=$$vRCtrimNumber($P(vobj(this,1),$C(124),6))
 .	S X=$P(vobj(this,1),$C(124),6) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OFFBID",$$^MSG(979,"CRCD.OFFBID"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),7)=""),'(+$P(vobj(this,1),$C(124),7)=$P(vobj(this,1),$C(124),7))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),7)=$$vRCtrimNumber($P(vobj(this,1),$C(124),7))
 .	S X=$P(vobj(this,1),$C(124),7) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OFFOFFER",$$^MSG(979,"CRCD.OFFOFFER"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),4)=""),'(+$P(vobj(this,1),$C(124),4)=$P(vobj(this,1),$C(124),4))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),4)=$$vRCtrimNumber($P(vobj(this,1),$C(124),4))
 .	S X=$P(vobj(this,1),$C(124),4) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OTCBID",$$^MSG(979,"CRCD.OTCBID"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),5)=""),'(+$P(vobj(this,1),$C(124),5)=$P(vobj(this,1),$C(124),5))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),5)=$$vRCtrimNumber($P(vobj(this,1),$C(124),5))
 .	S X=$P(vobj(this,1),$C(124),5) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OTCOFFER",$$^MSG(979,"CRCD.OTCOFFER"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),2)=""),'(+$P(vobj(this,1),$C(124),2)=$P(vobj(this,1),$C(124),2))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),2)=$$vRCtrimNumber($P(vobj(this,1),$C(124),2))
 .	S X=$P(vobj(this,1),$C(124),2) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("SPOTBID",$$^MSG(979,"CRCD.SPOTBID"_" "_errmsg))
 .	I '($P(vobj(this,1),$C(124),3)=""),'(+$P(vobj(this,1),$C(124),3)=$P(vobj(this,1),$C(124),3))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),3)=$$vRCtrimNumber($P(vobj(this,1),$C(124),3))
 .	S X=$P(vobj(this,1),$C(124),3) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("SPOTOFFER",$$^MSG(979,"CRCD.SPOTOFFER"_" "_errmsg))
 .	I '(($P(vobj(this,1),$C(124),10)=1)!($P(vobj(this,1),$C(124),10)=0)) D vRCvalidateDDerr("TERMS",$$^MSG(742,"L"))
 .	S X=$P(vobj(this,1),$C(124),12) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("TLM",$$^MSG(742,"C"))
 .	Q 
 I ($L(vobj(this,-3))>12) D vRCvalidateDDerr("CO",$$^MSG(1076,12))
 I ($L(vobj(this,-4))>3) D vRCvalidateDDerr("CRCD",$$^MSG(1076,3))
 I ($D(vobj(this))#2)!'($order(vobj(this,""))="") D
 .	I '(($P(vobj(this),$C(124),4)=1)!($P(vobj(this),$C(124),4)=0)) D vRCvalidateDDerr("BUY",$$^MSG(742,"L"))
 .	S X=$P(vobj(this),$C(124),10) I '(X=""),'$$vCaEx1() D vRCvalidateDDerr("CALENDAR",$$^MSG(1485,X))
 .	I '(($P(vobj(this),$C(124),11)=1)!($P(vobj(this),$C(124),11)=0)) D vRCvalidateDDerr("CASHCUR",$$^MSG(742,"L"))
 .	I ($L($P(vobj(this),$C(124),15))>20) D vRCvalidateDDerr("CHKDESC",$$^MSG(1076,20))
 .	S X=$P(vobj(this),$C(124),9) I '(X=""),'$$vCaEx2() D vRCvalidateDDerr("CNTRY",$$^MSG(1485,X))
 .	I '(($P(vobj(this),$C(124),20)=1)!($P(vobj(this),$C(124),20)=0)) D vRCvalidateDDerr("COACC",$$^MSG(742,"L"))
 .	I '(($P(vobj(this),$C(124),21)=1)!($P(vobj(this),$C(124),21)=0)) D vRCvalidateDDerr("CONV",$$^MSG(742,"L"))
 .	I ($L($P(vobj(this),$C(124),2))>3) D vRCvalidateDDerr("CRCDNO",$$^MSG(1076,3))
 .	I '($P(vobj(this),$C(124),7)=""),'(+$P(vobj(this),$C(124),7)=$P(vobj(this),$C(124),7))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),7)=$$vRCtrimNumber($P(vobj(this),$C(124),7))
 .	S X=$P(vobj(this),$C(124),7) I '(X=""),(X'?1N) D vRCvalidateDDerr("CURDEC",$$^MSG(742,"N"))
 .	I ($L($P(vobj(this),$C(124),1))>40) D vRCvalidateDDerr("DESC",$$^MSG(1076,40))
 .	I '(($P(vobj(this),$C(124),56)=1)!($P(vobj(this),$C(124),56)=0)) D vRCvalidateDDerr("EMU",$$^MSG(742,"L"))
 .	S X=$P(vobj(this),$C(124),59) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("EMUTED",$$^MSG(742,"D"))
 .	S X=$P(vobj(this),$C(124),58) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("EMUTSD",$$^MSG(742,"D"))
 .	I '($P(vobj(this),$C(124),53)=""),'(+$P(vobj(this),$C(124),53)=$P(vobj(this),$C(124),53))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),53)=$$vRCtrimNumber($P(vobj(this),$C(124),53))
 .	S X=$P(vobj(this),$C(124),53) I '(X="") S errmsg=$$VAL^DBSVER("N",12,0,,,,,6) I '(errmsg="") D vRCvalidateDDerr("EXCH",$$^MSG(979,"CRCD.EXCH"_" "_errmsg))
 .	I '($P(vobj(this),$C(124),57)=""),'(+$P(vobj(this),$C(124),57)=$P(vobj(this),$C(124),57))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),57)=$$vRCtrimNumber($P(vobj(this),$C(124),57))
 .	S X=$P(vobj(this),$C(124),57) I '(X="") S errmsg=$$VAL^DBSVER("N",12,0,,,,,7) I '(errmsg="") D vRCvalidateDDerr("FNCRATE",$$^MSG(979,"CRCD.FNCRATE"_" "_errmsg))
 .	I '($P(vobj(this),$C(124),45)=""),'(+$P(vobj(this),$C(124),45)=$P(vobj(this),$C(124),45))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),45)=$$vRCtrimNumber($P(vobj(this),$C(124),45))
 .	S X=$P(vobj(this),$C(124),45) I '(X=""),(X'?1.10N),(X'?1"-"1.9N) D vRCvalidateDDerr("FXVAR",$$^MSG(742,"N"))
 .	I '(($P(vobj(this),$C(124),40)=1)!($P(vobj(this),$C(124),40)=0)) D vRCvalidateDDerr("INTPMT",$$^MSG(742,"L"))
 .	I '($P(vobj(this),$C(124),14)=""),'(+$P(vobj(this),$C(124),14)=$P(vobj(this),$C(124),14))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),14)=$$vRCtrimNumber($P(vobj(this),$C(124),14))
 .	S X=$P(vobj(this),$C(124),14) I '(X="") S errmsg=$$VAL^DBSVER("N",12,1,,,,,6) I '(errmsg="") D vRCvalidateDDerr("MAXRATE",$$^MSG(979,"CRCD.MAXRATE"_" "_errmsg))
 .	I '($P(vobj(this),$C(124),18)=""),'(+$P(vobj(this),$C(124),18)=$P(vobj(this),$C(124),18))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),18)=$$vRCtrimNumber($P(vobj(this),$C(124),18))
 .	S X=$P(vobj(this),$C(124),18) I '(X="") S errmsg=$$VAL^DBSVER("$",12,,,,,,2) I '(errmsg="") D vRCvalidateDDerr("MINCASH",$$^MSG(979,"CRCD.MINCASH"_" "_errmsg))
 .	I '($P(vobj(this),$C(124),13)=""),'(+$P(vobj(this),$C(124),13)=$P(vobj(this),$C(124),13))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),13)=$$vRCtrimNumber($P(vobj(this),$C(124),13))
 .	S X=$P(vobj(this),$C(124),13) I '(X="") S errmsg=$$VAL^DBSVER("N",12,1,,,,,6) I '(errmsg="") D vRCvalidateDDerr("MINRATE",$$^MSG(979,"CRCD.MINRATE"_" "_errmsg))
 .	I '($P(vobj(this),$C(124),46)=""),'(+$P(vobj(this),$C(124),46)=$P(vobj(this),$C(124),46))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),46)=$$vRCtrimNumber($P(vobj(this),$C(124),46))
 .	S X=$P(vobj(this),$C(124),46) I '(X=""),(X'?1.12N),(X'?1"-"1.11N) D vRCvalidateDDerr("NOSTROFX",$$^MSG(742,"N"))
 .	I '($P(vobj(this),$C(124),37)=""),'(+$P(vobj(this),$C(124),37)=$P(vobj(this),$C(124),37))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),37)=$$vRCtrimNumber($P(vobj(this),$C(124),37))
 .	S X=$P(vobj(this),$C(124),37) I '(X=""),(X'?1.12N),(X'?1"-"1.11N) D vRCvalidateDDerr("OURPREF",$$^MSG(742,"N"))
 .	I '(($P(vobj(this),$C(124),19)=1)!($P(vobj(this),$C(124),19)=0)) D vRCvalidateDDerr("POACC",$$^MSG(742,"L"))
 .	I '($P(vobj(this),$C(124),8)=""),'(+$P(vobj(this),$C(124),8)=$P(vobj(this),$C(124),8))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),8)=$$vRCtrimNumber($P(vobj(this),$C(124),8))
 .	S X=$P(vobj(this),$C(124),8) I '(X=""),(X'?1N) D vRCvalidateDDerr("RATDEC",$$^MSG(742,"N"))
 .	I '(($P(vobj(this),$C(124),3)=1)!($P(vobj(this),$C(124),3)=0)) D vRCvalidateDDerr("RETAIL",$$^MSG(742,"L"))
 .	I '(($P(vobj(this),$C(124),5)=1)!($P(vobj(this),$C(124),5)=0)) D vRCvalidateDDerr("SELL",$$^MSG(742,"L"))
 .	I '($P(vobj(this),$C(124),36)=""),'(+$P(vobj(this),$C(124),36)=$P(vobj(this),$C(124),36))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),36)=$$vRCtrimNumber($P(vobj(this),$C(124),36))
 .	S X=$P(vobj(this),$C(124),36) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("SPTDYS",$$^MSG(742,"N"))
 .	I '(($P(vobj(this),$C(124),16)=1)!($P(vobj(this),$C(124),16)=0)) D vRCvalidateDDerr("SYSCEQ",$$^MSG(742,"L"))
 .	I '($P(vobj(this),$C(124),6)=""),'(+$P(vobj(this),$C(124),6)=$P(vobj(this),$C(124),6))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),6)=$$vRCtrimNumber($P(vobj(this),$C(124),6))
 .	S X=$P(vobj(this),$C(124),6) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("VARIANCE",$$^MSG(742,"N"))
 .	Q 
 Q 
 ;
vRCvalidateDD1(this) ; 
  S:'$D(vobj(this,1)) vobj(this,1)=$S(vobj(this,-2):$G(^CRCD(vobj(this,-3),vobj(this,-4),1)),1:"")
 N ER S ER=0
 N RM S RM=""
 N errmsg N X
 I ($D(vobj(this,1))#2) D
 .	I ($D(vobj(this,-100,1,"AVESPOTACCUM"))&($P($E($G(vobj(this,-100,1,"AVESPOTACCUM")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),9))),'($P(vobj(this,1),$C(124),9)=""),'(+$P(vobj(this,1),$C(124),9)=$P(vobj(this,1),$C(124),9))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),9)=$$vRCtrimNumber($P(vobj(this,1),$C(124),9))
 .	I ($D(vobj(this,-100,1,"AVESPOTACCUM"))&($P($E($G(vobj(this,-100,1,"AVESPOTACCUM")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),9))) S X=$P(vobj(this,1),$C(124),9) I '(X="") S errmsg=$$VAL^DBSVER("N",10,,,,,,5) I '(errmsg="") D vRCvalidateDDerr("AVESPOTACCUM",$$^MSG(979,"CRCD.AVESPOTACCUM"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"DLM"))&($P($E($G(vobj(this,-100,1,"DLM")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),11))) S X=$P(vobj(this,1),$C(124),11) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("DLM",$$^MSG(742,"D"))
 .	I ($D(vobj(this,-100,1,"FINSPOT"))&($P($E($G(vobj(this,-100,1,"FINSPOT")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),8))),'($P(vobj(this,1),$C(124),8)=""),'(+$P(vobj(this,1),$C(124),8)=$P(vobj(this,1),$C(124),8))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),8)=$$vRCtrimNumber($P(vobj(this,1),$C(124),8))
 .	I ($D(vobj(this,-100,1,"FINSPOT"))&($P($E($G(vobj(this,-100,1,"FINSPOT")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),8))) S X=$P(vobj(this,1),$C(124),8) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("FINSPOT",$$^MSG(979,"CRCD.FINSPOT"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"MIDRATE"))&($P($E($G(vobj(this,-100,1,"MIDRATE")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),1))),'($P(vobj(this,1),$C(124),1)=""),'(+$P(vobj(this,1),$C(124),1)=$P(vobj(this,1),$C(124),1))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),1)=$$vRCtrimNumber($P(vobj(this,1),$C(124),1))
 .	I ($D(vobj(this,-100,1,"MIDRATE"))&($P($E($G(vobj(this,-100,1,"MIDRATE")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),1))) S X=$P(vobj(this,1),$C(124),1) I '(X="") S errmsg=$$VAL^DBSVER("N",13,0,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("MIDRATE",$$^MSG(979,"CRCD.MIDRATE"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"OFFBID"))&($P($E($G(vobj(this,-100,1,"OFFBID")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),6))),'($P(vobj(this,1),$C(124),6)=""),'(+$P(vobj(this,1),$C(124),6)=$P(vobj(this,1),$C(124),6))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),6)=$$vRCtrimNumber($P(vobj(this,1),$C(124),6))
 .	I ($D(vobj(this,-100,1,"OFFBID"))&($P($E($G(vobj(this,-100,1,"OFFBID")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),6))) S X=$P(vobj(this,1),$C(124),6) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OFFBID",$$^MSG(979,"CRCD.OFFBID"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"OFFOFFER"))&($P($E($G(vobj(this,-100,1,"OFFOFFER")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),7))),'($P(vobj(this,1),$C(124),7)=""),'(+$P(vobj(this,1),$C(124),7)=$P(vobj(this,1),$C(124),7))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),7)=$$vRCtrimNumber($P(vobj(this,1),$C(124),7))
 .	I ($D(vobj(this,-100,1,"OFFOFFER"))&($P($E($G(vobj(this,-100,1,"OFFOFFER")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),7))) S X=$P(vobj(this,1),$C(124),7) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OFFOFFER",$$^MSG(979,"CRCD.OFFOFFER"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"OTCBID"))&($P($E($G(vobj(this,-100,1,"OTCBID")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),4))),'($P(vobj(this,1),$C(124),4)=""),'(+$P(vobj(this,1),$C(124),4)=$P(vobj(this,1),$C(124),4))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),4)=$$vRCtrimNumber($P(vobj(this,1),$C(124),4))
 .	I ($D(vobj(this,-100,1,"OTCBID"))&($P($E($G(vobj(this,-100,1,"OTCBID")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),4))) S X=$P(vobj(this,1),$C(124),4) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OTCBID",$$^MSG(979,"CRCD.OTCBID"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"OTCOFFER"))&($P($E($G(vobj(this,-100,1,"OTCOFFER")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),5))),'($P(vobj(this,1),$C(124),5)=""),'(+$P(vobj(this,1),$C(124),5)=$P(vobj(this,1),$C(124),5))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),5)=$$vRCtrimNumber($P(vobj(this,1),$C(124),5))
 .	I ($D(vobj(this,-100,1,"OTCOFFER"))&($P($E($G(vobj(this,-100,1,"OTCOFFER")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),5))) S X=$P(vobj(this,1),$C(124),5) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("OTCOFFER",$$^MSG(979,"CRCD.OTCOFFER"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"SPOTBID"))&($P($E($G(vobj(this,-100,1,"SPOTBID")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),2))),'($P(vobj(this,1),$C(124),2)=""),'(+$P(vobj(this,1),$C(124),2)=$P(vobj(this,1),$C(124),2))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),2)=$$vRCtrimNumber($P(vobj(this,1),$C(124),2))
 .	I ($D(vobj(this,-100,1,"SPOTBID"))&($P($E($G(vobj(this,-100,1,"SPOTBID")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),2))) S X=$P(vobj(this,1),$C(124),2) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("SPOTBID",$$^MSG(979,"CRCD.SPOTBID"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"SPOTOFFER"))&($P($E($G(vobj(this,-100,1,"SPOTOFFER")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),3))),'($P(vobj(this,1),$C(124),3)=""),'(+$P(vobj(this,1),$C(124),3)=$P(vobj(this,1),$C(124),3))  S vobj(this,-100,1)="" S $P(vobj(this,1),$C(124),3)=$$vRCtrimNumber($P(vobj(this,1),$C(124),3))
 .	I ($D(vobj(this,-100,1,"SPOTOFFER"))&($P($E($G(vobj(this,-100,1,"SPOTOFFER")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),3))) S X=$P(vobj(this,1),$C(124),3) I '(X="") S errmsg=$$VAL^DBSVER("N",13,,,,.0000001,,7) I '(errmsg="") D vRCvalidateDDerr("SPOTOFFER",$$^MSG(979,"CRCD.SPOTOFFER"_" "_errmsg))
 .	I ($D(vobj(this,-100,1,"TERMS"))&($P($E($G(vobj(this,-100,1,"TERMS")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),10))) I '(($P(vobj(this,1),$C(124),10)=1)!($P(vobj(this,1),$C(124),10)=0)) D vRCvalidateDDerr("TERMS",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,1,"TLM"))&($P($E($G(vobj(this,-100,1,"TLM")),5,9999),$C(124))'=$P(vobj(this,1),$C(124),12))) S X=$P(vobj(this,1),$C(124),12) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("TLM",$$^MSG(742,"C"))
 .	Q 
 I ($D(vobj(this,-100,"1*","CO"))&($P($E($G(vobj(this,-100,"1*","CO")),5,9999),$C(124))'=vobj(this,-3))) I ($L(vobj(this,-3))>12) D vRCvalidateDDerr("CO",$$^MSG(1076,12))
 I ($D(vobj(this,-100,"2*","CRCD"))&($P($E($G(vobj(this,-100,"2*","CRCD")),5,9999),$C(124))'=vobj(this,-4))) I ($L(vobj(this,-4))>3) D vRCvalidateDDerr("CRCD",$$^MSG(1076,3))
 I ($D(vobj(this))#2)!'($order(vobj(this,""))="") D
 .	I ($D(vobj(this,-100,"0*","BUY"))&($P($E($G(vobj(this,-100,"0*","BUY")),5,9999),$C(124))'=$P(vobj(this),$C(124),4))) I '(($P(vobj(this),$C(124),4)=1)!($P(vobj(this),$C(124),4)=0)) D vRCvalidateDDerr("BUY",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","CALENDAR"))&($P($E($G(vobj(this,-100,"0*","CALENDAR")),5,9999),$C(124))'=$P(vobj(this),$C(124),10))) S X=$P(vobj(this),$C(124),10) I '(X=""),'$$vCaEx3() D vRCvalidateDDerr("CALENDAR",$$^MSG(1485,X))
 .	I ($D(vobj(this,-100,"0*","CASHCUR"))&($P($E($G(vobj(this,-100,"0*","CASHCUR")),5,9999),$C(124))'=$P(vobj(this),$C(124),11))) I '(($P(vobj(this),$C(124),11)=1)!($P(vobj(this),$C(124),11)=0)) D vRCvalidateDDerr("CASHCUR",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","CHKDESC"))&($P($E($G(vobj(this,-100,"0*","CHKDESC")),5,9999),$C(124))'=$P(vobj(this),$C(124),15))) I ($L($P(vobj(this),$C(124),15))>20) D vRCvalidateDDerr("CHKDESC",$$^MSG(1076,20))
 .	I ($D(vobj(this,-100,"0*","CNTRY"))&($P($E($G(vobj(this,-100,"0*","CNTRY")),5,9999),$C(124))'=$P(vobj(this),$C(124),9))) S X=$P(vobj(this),$C(124),9) I '(X=""),'$$vCaEx4() D vRCvalidateDDerr("CNTRY",$$^MSG(1485,X))
 .	I ($D(vobj(this,-100,"0*","COACC"))&($P($E($G(vobj(this,-100,"0*","COACC")),5,9999),$C(124))'=$P(vobj(this),$C(124),20))) I '(($P(vobj(this),$C(124),20)=1)!($P(vobj(this),$C(124),20)=0)) D vRCvalidateDDerr("COACC",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","CONV"))&($P($E($G(vobj(this,-100,"0*","CONV")),5,9999),$C(124))'=$P(vobj(this),$C(124),21))) I '(($P(vobj(this),$C(124),21)=1)!($P(vobj(this),$C(124),21)=0)) D vRCvalidateDDerr("CONV",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","CRCDNO"))&($P($E($G(vobj(this,-100,"0*","CRCDNO")),5,9999),$C(124))'=$P(vobj(this),$C(124),2))) I ($L($P(vobj(this),$C(124),2))>3) D vRCvalidateDDerr("CRCDNO",$$^MSG(1076,3))
 .	I ($D(vobj(this,-100,"0*","CURDEC"))&($P($E($G(vobj(this,-100,"0*","CURDEC")),5,9999),$C(124))'=$P(vobj(this),$C(124),7))),'($P(vobj(this),$C(124),7)=""),'(+$P(vobj(this),$C(124),7)=$P(vobj(this),$C(124),7))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),7)=$$vRCtrimNumber($P(vobj(this),$C(124),7))
 .	I ($D(vobj(this,-100,"0*","CURDEC"))&($P($E($G(vobj(this,-100,"0*","CURDEC")),5,9999),$C(124))'=$P(vobj(this),$C(124),7))) S X=$P(vobj(this),$C(124),7) I '(X=""),(X'?1N) D vRCvalidateDDerr("CURDEC",$$^MSG(742,"N"))
 .	I ($D(vobj(this,-100,"0*","DESC"))&($P($E($G(vobj(this,-100,"0*","DESC")),5,9999),$C(124))'=$P(vobj(this),$C(124),1))) I ($L($P(vobj(this),$C(124),1))>40) D vRCvalidateDDerr("DESC",$$^MSG(1076,40))
 .	I ($D(vobj(this,-100,"0*","EMU"))&($P($E($G(vobj(this,-100,"0*","EMU")),5,9999),$C(124))'=$P(vobj(this),$C(124),56))) I '(($P(vobj(this),$C(124),56)=1)!($P(vobj(this),$C(124),56)=0)) D vRCvalidateDDerr("EMU",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","EMUTED"))&($P($E($G(vobj(this,-100,"0*","EMUTED")),5,9999),$C(124))'=$P(vobj(this),$C(124),59))) S X=$P(vobj(this),$C(124),59) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("EMUTED",$$^MSG(742,"D"))
 .	I ($D(vobj(this,-100,"0*","EMUTSD"))&($P($E($G(vobj(this,-100,"0*","EMUTSD")),5,9999),$C(124))'=$P(vobj(this),$C(124),58))) S X=$P(vobj(this),$C(124),58) I '(X=""),(X'?1.5N) D vRCvalidateDDerr("EMUTSD",$$^MSG(742,"D"))
 .	I ($D(vobj(this,-100,"0*","EXCH"))&($P($E($G(vobj(this,-100,"0*","EXCH")),5,9999),$C(124))'=$P(vobj(this),$C(124),53))),'($P(vobj(this),$C(124),53)=""),'(+$P(vobj(this),$C(124),53)=$P(vobj(this),$C(124),53))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),53)=$$vRCtrimNumber($P(vobj(this),$C(124),53))
 .	I ($D(vobj(this,-100,"0*","EXCH"))&($P($E($G(vobj(this,-100,"0*","EXCH")),5,9999),$C(124))'=$P(vobj(this),$C(124),53))) S X=$P(vobj(this),$C(124),53) I '(X="") S errmsg=$$VAL^DBSVER("N",12,0,,,,,6) I '(errmsg="") D vRCvalidateDDerr("EXCH",$$^MSG(979,"CRCD.EXCH"_" "_errmsg))
 .	I ($D(vobj(this,-100,"0*","FNCRATE"))&($P($E($G(vobj(this,-100,"0*","FNCRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),57))),'($P(vobj(this),$C(124),57)=""),'(+$P(vobj(this),$C(124),57)=$P(vobj(this),$C(124),57))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),57)=$$vRCtrimNumber($P(vobj(this),$C(124),57))
 .	I ($D(vobj(this,-100,"0*","FNCRATE"))&($P($E($G(vobj(this,-100,"0*","FNCRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),57))) S X=$P(vobj(this),$C(124),57) I '(X="") S errmsg=$$VAL^DBSVER("N",12,0,,,,,7) I '(errmsg="") D vRCvalidateDDerr("FNCRATE",$$^MSG(979,"CRCD.FNCRATE"_" "_errmsg))
 .	I ($D(vobj(this,-100,"0*","FXVAR"))&($P($E($G(vobj(this,-100,"0*","FXVAR")),5,9999),$C(124))'=$P(vobj(this),$C(124),45))),'($P(vobj(this),$C(124),45)=""),'(+$P(vobj(this),$C(124),45)=$P(vobj(this),$C(124),45))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),45)=$$vRCtrimNumber($P(vobj(this),$C(124),45))
 .	I ($D(vobj(this,-100,"0*","FXVAR"))&($P($E($G(vobj(this,-100,"0*","FXVAR")),5,9999),$C(124))'=$P(vobj(this),$C(124),45))) S X=$P(vobj(this),$C(124),45) I '(X=""),(X'?1.10N),(X'?1"-"1.9N) D vRCvalidateDDerr("FXVAR",$$^MSG(742,"N"))
 .	I ($D(vobj(this,-100,"0*","INTPMT"))&($P($E($G(vobj(this,-100,"0*","INTPMT")),5,9999),$C(124))'=$P(vobj(this),$C(124),40))) I '(($P(vobj(this),$C(124),40)=1)!($P(vobj(this),$C(124),40)=0)) D vRCvalidateDDerr("INTPMT",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","MAXRATE"))&($P($E($G(vobj(this,-100,"0*","MAXRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),14))),'($P(vobj(this),$C(124),14)=""),'(+$P(vobj(this),$C(124),14)=$P(vobj(this),$C(124),14))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),14)=$$vRCtrimNumber($P(vobj(this),$C(124),14))
 .	I ($D(vobj(this,-100,"0*","MAXRATE"))&($P($E($G(vobj(this,-100,"0*","MAXRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),14))) S X=$P(vobj(this),$C(124),14) I '(X="") S errmsg=$$VAL^DBSVER("N",12,1,,,,,6) I '(errmsg="") D vRCvalidateDDerr("MAXRATE",$$^MSG(979,"CRCD.MAXRATE"_" "_errmsg))
 .	I ($D(vobj(this,-100,"0*","MINCASH"))&($P($E($G(vobj(this,-100,"0*","MINCASH")),5,9999),$C(124))'=$P(vobj(this),$C(124),18))),'($P(vobj(this),$C(124),18)=""),'(+$P(vobj(this),$C(124),18)=$P(vobj(this),$C(124),18))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),18)=$$vRCtrimNumber($P(vobj(this),$C(124),18))
 .	I ($D(vobj(this,-100,"0*","MINCASH"))&($P($E($G(vobj(this,-100,"0*","MINCASH")),5,9999),$C(124))'=$P(vobj(this),$C(124),18))) S X=$P(vobj(this),$C(124),18) I '(X="") S errmsg=$$VAL^DBSVER("$",12,,,,,,2) I '(errmsg="") D vRCvalidateDDerr("MINCASH",$$^MSG(979,"CRCD.MINCASH"_" "_errmsg))
 .	I ($D(vobj(this,-100,"0*","MINRATE"))&($P($E($G(vobj(this,-100,"0*","MINRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),13))),'($P(vobj(this),$C(124),13)=""),'(+$P(vobj(this),$C(124),13)=$P(vobj(this),$C(124),13))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),13)=$$vRCtrimNumber($P(vobj(this),$C(124),13))
 .	I ($D(vobj(this,-100,"0*","MINRATE"))&($P($E($G(vobj(this,-100,"0*","MINRATE")),5,9999),$C(124))'=$P(vobj(this),$C(124),13))) S X=$P(vobj(this),$C(124),13) I '(X="") S errmsg=$$VAL^DBSVER("N",12,1,,,,,6) I '(errmsg="") D vRCvalidateDDerr("MINRATE",$$^MSG(979,"CRCD.MINRATE"_" "_errmsg))
 .	I ($D(vobj(this,-100,"0*","NOSTROFX"))&($P($E($G(vobj(this,-100,"0*","NOSTROFX")),5,9999),$C(124))'=$P(vobj(this),$C(124),46))),'($P(vobj(this),$C(124),46)=""),'(+$P(vobj(this),$C(124),46)=$P(vobj(this),$C(124),46))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),46)=$$vRCtrimNumber($P(vobj(this),$C(124),46))
 .	I ($D(vobj(this,-100,"0*","NOSTROFX"))&($P($E($G(vobj(this,-100,"0*","NOSTROFX")),5,9999),$C(124))'=$P(vobj(this),$C(124),46))) S X=$P(vobj(this),$C(124),46) I '(X=""),(X'?1.12N),(X'?1"-"1.11N) D vRCvalidateDDerr("NOSTROFX",$$^MSG(742,"N"))
 .	I ($D(vobj(this,-100,"0*","OURPREF"))&($P($E($G(vobj(this,-100,"0*","OURPREF")),5,9999),$C(124))'=$P(vobj(this),$C(124),37))),'($P(vobj(this),$C(124),37)=""),'(+$P(vobj(this),$C(124),37)=$P(vobj(this),$C(124),37))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),37)=$$vRCtrimNumber($P(vobj(this),$C(124),37))
 .	I ($D(vobj(this,-100,"0*","OURPREF"))&($P($E($G(vobj(this,-100,"0*","OURPREF")),5,9999),$C(124))'=$P(vobj(this),$C(124),37))) S X=$P(vobj(this),$C(124),37) I '(X=""),(X'?1.12N),(X'?1"-"1.11N) D vRCvalidateDDerr("OURPREF",$$^MSG(742,"N"))
 .	I ($D(vobj(this,-100,"0*","POACC"))&($P($E($G(vobj(this,-100,"0*","POACC")),5,9999),$C(124))'=$P(vobj(this),$C(124),19))) I '(($P(vobj(this),$C(124),19)=1)!($P(vobj(this),$C(124),19)=0)) D vRCvalidateDDerr("POACC",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","RATDEC"))&($P($E($G(vobj(this,-100,"0*","RATDEC")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))),'($P(vobj(this),$C(124),8)=""),'(+$P(vobj(this),$C(124),8)=$P(vobj(this),$C(124),8))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),8)=$$vRCtrimNumber($P(vobj(this),$C(124),8))
 .	I ($D(vobj(this,-100,"0*","RATDEC"))&($P($E($G(vobj(this,-100,"0*","RATDEC")),5,9999),$C(124))'=$P(vobj(this),$C(124),8))) S X=$P(vobj(this),$C(124),8) I '(X=""),(X'?1N) D vRCvalidateDDerr("RATDEC",$$^MSG(742,"N"))
 .	I ($D(vobj(this,-100,"0*","RETAIL"))&($P($E($G(vobj(this,-100,"0*","RETAIL")),5,9999),$C(124))'=$P(vobj(this),$C(124),3))) I '(($P(vobj(this),$C(124),3)=1)!($P(vobj(this),$C(124),3)=0)) D vRCvalidateDDerr("RETAIL",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","SELL"))&($P($E($G(vobj(this,-100,"0*","SELL")),5,9999),$C(124))'=$P(vobj(this),$C(124),5))) I '(($P(vobj(this),$C(124),5)=1)!($P(vobj(this),$C(124),5)=0)) D vRCvalidateDDerr("SELL",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","SPTDYS"))&($P($E($G(vobj(this,-100,"0*","SPTDYS")),5,9999),$C(124))'=$P(vobj(this),$C(124),36))),'($P(vobj(this),$C(124),36)=""),'(+$P(vobj(this),$C(124),36)=$P(vobj(this),$C(124),36))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),36)=$$vRCtrimNumber($P(vobj(this),$C(124),36))
 .	I ($D(vobj(this,-100,"0*","SPTDYS"))&($P($E($G(vobj(this,-100,"0*","SPTDYS")),5,9999),$C(124))'=$P(vobj(this),$C(124),36))) S X=$P(vobj(this),$C(124),36) I '(X=""),(X'?1.4N),(X'?1"-"1.3N) D vRCvalidateDDerr("SPTDYS",$$^MSG(742,"N"))
 .	I ($D(vobj(this,-100,"0*","SYSCEQ"))&($P($E($G(vobj(this,-100,"0*","SYSCEQ")),5,9999),$C(124))'=$P(vobj(this),$C(124),16))) I '(($P(vobj(this),$C(124),16)=1)!($P(vobj(this),$C(124),16)=0)) D vRCvalidateDDerr("SYSCEQ",$$^MSG(742,"L"))
 .	I ($D(vobj(this,-100,"0*","VARIANCE"))&($P($E($G(vobj(this,-100,"0*","VARIANCE")),5,9999),$C(124))'=$P(vobj(this),$C(124),6))),'($P(vobj(this),$C(124),6)=""),'(+$P(vobj(this),$C(124),6)=$P(vobj(this),$C(124),6))  S vobj(this,-100,"0*")="" S $P(vobj(this),$C(124),6)=$$vRCtrimNumber($P(vobj(this),$C(124),6))
 .	I ($D(vobj(this,-100,"0*","VARIANCE"))&($P($E($G(vobj(this,-100,"0*","VARIANCE")),5,9999),$C(124))'=$P(vobj(this),$C(124),6))) S X=$P(vobj(this),$C(124),6) I '(X=""),(X'?1.2N),(X'?1"-"1.1N) D vRCvalidateDDerr("VARIANCE",$$^MSG(742,"N"))
 .	Q 
 Q 
 ;
vRCvalidateDDerr(column,errmsg) ; 
 N ER S ER=0
 N RM S RM=""
 D SETERR^DBSEXECU("CRCD","MSG",979,"CRCD."_column_" "_errmsg)
 I ER D throwError($get(RM))
 Q 
 ;
vRCtrimNumber(str) ; 
 I ($E(str,1)="0") S str=$$vStrTrim(str,-1,"0") I (str="") S str="0"
 I (str["."),($E(str,$L(str))="0") S str=$$RTCHR^%ZFUNC(str,"0") I ($E(str,$L(str))=".") S str=$E(str,1,$L(str)-1) I (str="") S str="0"
 Q str
 ;
vRCkeyChanged(this,vRCparams,vRCaudit) ; 
 N vTp
 N newkeys N oldkeys N vRCauditIns
 N newKey1 S newKey1=vobj(this,-3)
 N oldKey1 S oldKey1=$S($D(vobj(this,-100,"1*","CO")):$P($E(vobj(this,-100,"1*","CO"),5,9999),$C(124)),1:vobj(this,-3))
 N newKey2 S newKey2=vobj(this,-4)
 N oldKey2 S oldKey2=$S($D(vobj(this,-100,"2*","CRCD")):$P($E(vobj(this,-100,"2*","CRCD"),5,9999),$C(124)),1:vobj(this,-4))
  N V1,V2 S V1=vobj(this,-3),V2=vobj(this,-4) I ($D(^CRCD(V1,V2))) D throwError($$^MSG(2327))
 S newkeys=newKey1_","_newKey2
 S oldkeys=oldKey1_","_oldKey2
  S vobj(this,-3)=oldKey1
  S vobj(this,-4)=oldKey2
 S vRCparams=$$setPar^UCUTILN(vRCparams,"NOINDEX")
 D vRCforceLoad(this)
 I (("/"_vRCparams_"/")["/VALREQ/") D vRCchkReqForInsert(this)
 I (("/"_vRCparams_"/")["/VALDD/") D vRCvalidateDD(this,1)
 D vRCmiscValidations(this,vRCparams,1)
 D vRCupdateDB(this,1,vRCparams,.vRCaudit,.vRCauditIns)
  S vobj(this,-3)=newKey1
  S vobj(this,-4)=newKey2
 N newrec S newrec=$$vReCp1(this)
 S vobj(newrec,-2)=0
 S vTp=($TL=0) TS:vTp (vobj):transactionid="CS" D vSave^RecordCRCD(newrec,$$initPar^UCUTILN($$initPar^UCUTILN("/NOVAL/NOCASDEL/NOJOURNAL/NOTRIGBEF/NOTRIGAFT/"))) K vobj(newrec,-100) S vobj(newrec,-2)=1 TC:vTp  
 D
 .	N %O S %O=1
 .	N ER S ER=0
 .	N RM S RM=""
 .	;   #ACCEPT Date=10/24/2008; Pgm=RussellDS; CR=30801; Group=ACCESS
 .	D CASUPD^DBSEXECU("CRCD",oldkeys,newkeys)
 .	I ER D throwError($get(RM))
 .	Q 
  S vobj(this,-3)=oldKey1
  S vobj(this,-4)=oldKey2
 S vRCparams=$$initPar^UCUTILN("/NOVAL/NOCASDEL/NOJOURNAL/NOTRIGBEF/NOTRIGAFT/")
 D vRCdelete(this,vRCparams,.vRCaudit,1)
  S vobj(this,-3)=newKey1
  S vobj(this,-4)=newKey2
 K vobj(+$G(newrec)) Q 
 ;
throwError(MSG) ; 
 S $ZE="0,"_$ZPOS_","_"%PSL-E-DBFILER,"_$translate(MSG,",","~"),$EC=",U1001,"
 Q 
 ; ----------------
 ;  #OPTION ResultClass 1
vStrRep(object,p1,p2,p3,p4,qt) ; String.replace
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 ;
 I p3<0 Q object
 I $L(p1)=1,$L(p2)<2,'p3,'p4,(qt="") Q $translate(object,p1,p2)
 ;
 N y S y=0
 F  S y=$$vStrFnd(object,p1,y,p4,qt) Q:y=0  D
 .	S object=$E(object,1,y-$L(p1)-1)_p2_$E(object,y,1048575)
 .	S y=y+$L(p2)-$L(p1)
 .	I p3 S p3=p3-1 I p3=0 S y=$L(object)+1
 .	Q 
 Q object
 ; ----------------
 ;  #OPTION ResultClass 1
vCaEx1() ; {Cache}%CACHE("UTBLNBD").isDefined("UTBLNBD","NBDC=:X")
 N vret
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 N vRec,vop1 S vRec=$$vCa3(X,.vop1)
 S vret=$G(vop1)=1 Q vret
 ; ----------------
 ;  #OPTION ResultClass 1
vCaEx2() ; {Cache}%CACHE("STBLCNTRY").isDefined("STBLCNTRY","CNTRY=:X")
 N vret
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 N vRec,vop1 S vRec=$$vCa4(X,.vop1)
 S vret=$G(vop1)=1 Q vret
 ; ----------------
 ;  #OPTION ResultClass 1
vCaEx3() ; {Cache}%CACHE("UTBLNBD").isDefined("UTBLNBD","NBDC=:X")
 N vret
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 N vRec,vop1 S vRec=$$vCa3(X,.vop1)
 S vret=$G(vop1)=1 Q vret
 ; ----------------
 ;  #OPTION ResultClass 1
vCaEx4() ; {Cache}%CACHE("STBLCNTRY").isDefined("STBLCNTRY","CNTRY=:X")
 N vret
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 N vRec,vop1 S vRec=$$vCa4(X,.vop1)
 S vret=$G(vop1)=1 Q vret
 ; ----------------
 ;  #OPTION ResultClass 1
vStrTrim(object,p1,p2) ; String.trim
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 I p1'<0 S object=$$RTCHR^%ZFUNC(object,p2)
 I p1'>0 F  Q:$E(object,1)'=p2  S object=$E(object,2,1048575)
 Q object
 ; ----------------
 ;  #OPTION ResultClass 1
vStrFnd(object,p1,p2,p3,qt) ; String.find
 ;
 ;  #OPTIMIZE FUNCTIONS OFF
 ;
 I (p1="") Q $S(p2<1:1,1:+p2)
 I p3 S object=$ZCONVERT(object,"U") S p1=$ZCONVERT(p1,"U")
 S p2=$F(object,p1,p2)
 I '(qt=""),$L($E(object,1,p2-1),qt)#2=0 D
 .	F  S p2=$F(object,p1,p2) Q:p2=0!($L($E(object,1,p2-1),qt)#2) 
 .	Q 
 Q p2
 ;
vCa3(v1,v2out) ; voXN = ({Cache}%CACHE("UTBLNBD").getRecord(UTBLNBD,1)
 ;
 I '$D(%CACHE("UTBLNBD",v1)) D
 .  I $G(%CACHE("UTBLNBD"))>100 KILL %CACHE("UTBLNBD")
 .  S %CACHE("UTBLNBD")=$G(%CACHE("UTBLNBD"))+1
 .  S %CACHE("UTBLNBD",v1)=$$vRCgetRecord1Opt^RecordUTBLNBD(v1,0,.v2out),%CACHE("UTBLNBD",v1,-2)=v2out
 ;
 ;
 E  S v2out=%CACHE("UTBLNBD",v1,-2)
 Q %CACHE("UTBLNBD",v1)
 ;
vCa4(v1,v2out) ; voXN = ({Cache}%CACHE("STBLCNTRY").getRecord(STBLCNTRY,1)
 ;
 I '$D(%CACHE("STBLCNTRY",v1)) D
 .  I $G(%CACHE("STBLCNTRY"))>100 KILL %CACHE("STBLCNTRY")
 .  S %CACHE("STBLCNTRY")=$G(%CACHE("STBLCNTRY"))+1
 .  S %CACHE("STBLCNTRY",v1)=$$vRCgetRecord1Opt^RecordSTBLCNTRY(v1,0,.v2out),%CACHE("STBLCNTRY",v1,-2)=v2out
 ;
 ;
 E  S v2out=%CACHE("STBLCNTRY",v1,-2)
 Q %CACHE("STBLCNTRY",v1)
 ;
vReCp1(v1) ; RecordCRCD.copy: CRCD
 ;
 N vNod,vOid
 I $G(vobj(v1,-2)) D
 .	F vNod=1 S:'$D(vobj(v1,vNod)) vobj(v1,vNod)=$G(^CRCD(vobj(v1,-3),vobj(v1,-4),vNod))
 S vOid=$$copy^UCGMR(v1)
 Q vOid
