#
#	Copyright (C) 1995 - Sanchez Computer Associates
#
#	$Id$
#	$Log:	Makefile,v $
# Revision 1.5  96/03/21  15:07:27  15:07:27  zengf (Fan Zeng)
# makefile for both APIs and mtm.
# 
#	$Revision: 1.5 $
#
#
#
#
#
#
#
all:	clean api mtm

api:
	make -f api.mk

mtm:
	rm -f *.o
	make -f mtm.mk

clean:
	rm -f *.o
	rm -f mtm

# DO NOT DELETE THIS LINE
